// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.1
// source: api/social/social.proto

package social

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FriendRequestStatus - статус заявки в друзья
type FriendRequestStatus int32

const (
	FriendRequestStatus_FRIEND_REQUEST_STATUS_PENDING  FriendRequestStatus = 0
	FriendRequestStatus_FRIEND_REQUEST_STATUS_ACCEPTED FriendRequestStatus = 1
	FriendRequestStatus_FRIEND_REQUEST_STATUS_DECLINED FriendRequestStatus = 2
)

// Enum value maps for FriendRequestStatus.
var (
	FriendRequestStatus_name = map[int32]string{
		0: "FRIEND_REQUEST_STATUS_PENDING",
		1: "FRIEND_REQUEST_STATUS_ACCEPTED",
		2: "FRIEND_REQUEST_STATUS_DECLINED",
	}
	FriendRequestStatus_value = map[string]int32{
		"FRIEND_REQUEST_STATUS_PENDING":  0,
		"FRIEND_REQUEST_STATUS_ACCEPTED": 1,
		"FRIEND_REQUEST_STATUS_DECLINED": 2,
	}
)

func (x FriendRequestStatus) Enum() *FriendRequestStatus {
	p := new(FriendRequestStatus)
	*p = x
	return p
}

func (x FriendRequestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FriendRequestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_social_social_proto_enumTypes[0].Descriptor()
}

func (FriendRequestStatus) Type() protoreflect.EnumType {
	return &file_api_social_social_proto_enumTypes[0]
}

func (x FriendRequestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FriendRequestStatus.Descriptor instead.
func (FriendRequestStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_social_social_proto_rawDescGZIP(), []int{0}
}

// FriendRequest - заявка в друзья
type FriendRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// requestId - идентификатор заявки
	RequestId string `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	// fromUserId - идентификатор пользователя, отправившего заявку
	FromUserId string `protobuf:"bytes,2,opt,name=fromUserId,proto3" json:"fromUserId,omitempty"`
	// toUserId - идентификатор пользователя, получающего заявку
	ToUserId string `protobuf:"bytes,3,opt,name=toUserId,proto3" json:"toUserId,omitempty"`
	// status - статус заявки
	Status        FriendRequestStatus `protobuf:"varint,4,opt,name=status,proto3,enum=github.com.krus210.balun_microservices.protobuf.social.v1.proto.FriendRequestStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRequest) Reset() {
	*x = FriendRequest{}
	mi := &file_api_social_social_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequest) ProtoMessage() {}

func (x *FriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_social_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequest.ProtoReflect.Descriptor instead.
func (*FriendRequest) Descriptor() ([]byte, []int) {
	return file_api_social_social_proto_rawDescGZIP(), []int{0}
}

func (x *FriendRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FriendRequest) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *FriendRequest) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *FriendRequest) GetStatus() FriendRequestStatus {
	if x != nil {
		return x.Status
	}
	return FriendRequestStatus_FRIEND_REQUEST_STATUS_PENDING
}

// SendFriendRequestRequest - запрос SendFriendRequest
type SendFriendRequestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// toUserId - идентификатор пользователя, получающего заявку
	ToUserId      string `protobuf:"bytes,1,opt,name=toUserId,proto3" json:"toUserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestRequest) Reset() {
	*x = SendFriendRequestRequest{}
	mi := &file_api_social_social_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestRequest) ProtoMessage() {}

func (x *SendFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_social_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*SendFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_api_social_social_proto_rawDescGZIP(), []int{1}
}

func (x *SendFriendRequestRequest) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

// SendFriendRequestResponse - ответ SendFriendRequest
type SendFriendRequestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// friendRequest - заявка в друзья
	FriendRequest *FriendRequest `protobuf:"bytes,1,opt,name=friendRequest,proto3" json:"friendRequest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestResponse) Reset() {
	*x = SendFriendRequestResponse{}
	mi := &file_api_social_social_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestResponse) ProtoMessage() {}

func (x *SendFriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_social_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestResponse.ProtoReflect.Descriptor instead.
func (*SendFriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_api_social_social_proto_rawDescGZIP(), []int{2}
}

func (x *SendFriendRequestResponse) GetFriendRequest() *FriendRequest {
	if x != nil {
		return x.FriendRequest
	}
	return nil
}

// ListRequestsRequest - запрос ListRequests
type ListRequestsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// toUserId - идентификатор пользователя получающего заявку
	ToUserId      string `protobuf:"bytes,1,opt,name=toUserId,proto3" json:"toUserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequestsRequest) Reset() {
	*x = ListRequestsRequest{}
	mi := &file_api_social_social_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequestsRequest) ProtoMessage() {}

func (x *ListRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_social_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequestsRequest.ProtoReflect.Descriptor instead.
func (*ListRequestsRequest) Descriptor() ([]byte, []int) {
	return file_api_social_social_proto_rawDescGZIP(), []int{3}
}

func (x *ListRequestsRequest) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

// ListRequestsResponse - ответ ListRequests
type ListRequestsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// requests - список заявок в друзья
	Requests      []*FriendRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequestsResponse) Reset() {
	*x = ListRequestsResponse{}
	mi := &file_api_social_social_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequestsResponse) ProtoMessage() {}

func (x *ListRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_social_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListRequestsResponse) Descriptor() ([]byte, []int) {
	return file_api_social_social_proto_rawDescGZIP(), []int{4}
}

func (x *ListRequestsResponse) GetRequests() []*FriendRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

// AcceptFriendRequestRequest - запрос AcceptFriendRequest
type AcceptFriendRequestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// requestId - идентификатор заявки
	RequestId     string `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFriendRequestRequest) Reset() {
	*x = AcceptFriendRequestRequest{}
	mi := &file_api_social_social_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendRequestRequest) ProtoMessage() {}

func (x *AcceptFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_social_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*AcceptFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_api_social_social_proto_rawDescGZIP(), []int{5}
}

func (x *AcceptFriendRequestRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// AcceptFriendRequestResponse - ответ AcceptFriendRequest
type AcceptFriendRequestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// friendRequest - заявка в друзья
	FriendRequest *FriendRequest `protobuf:"bytes,1,opt,name=friendRequest,proto3" json:"friendRequest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFriendRequestResponse) Reset() {
	*x = AcceptFriendRequestResponse{}
	mi := &file_api_social_social_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendRequestResponse) ProtoMessage() {}

func (x *AcceptFriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_social_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendRequestResponse.ProtoReflect.Descriptor instead.
func (*AcceptFriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_api_social_social_proto_rawDescGZIP(), []int{6}
}

func (x *AcceptFriendRequestResponse) GetFriendRequest() *FriendRequest {
	if x != nil {
		return x.FriendRequest
	}
	return nil
}

// DeclineFriendRequestRequest - запрос DeclineFriendRequest
type DeclineFriendRequestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// requestId - идентификатор заявки
	RequestId     string `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclineFriendRequestRequest) Reset() {
	*x = DeclineFriendRequestRequest{}
	mi := &file_api_social_social_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclineFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineFriendRequestRequest) ProtoMessage() {}

func (x *DeclineFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_social_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*DeclineFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_api_social_social_proto_rawDescGZIP(), []int{7}
}

func (x *DeclineFriendRequestRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// DeclineFriendRequestResponse - ответ DeclineFriendRequest
type DeclineFriendRequestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// friendRequest - заявка в друзья
	FriendRequest *FriendRequest `protobuf:"bytes,1,opt,name=friendRequest,proto3" json:"friendRequest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclineFriendRequestResponse) Reset() {
	*x = DeclineFriendRequestResponse{}
	mi := &file_api_social_social_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclineFriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineFriendRequestResponse) ProtoMessage() {}

func (x *DeclineFriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_social_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineFriendRequestResponse.ProtoReflect.Descriptor instead.
func (*DeclineFriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_api_social_social_proto_rawDescGZIP(), []int{8}
}

func (x *DeclineFriendRequestResponse) GetFriendRequest() *FriendRequest {
	if x != nil {
		return x.FriendRequest
	}
	return nil
}

// RemoveFriendRequest - запрос RemoveFriend
type RemoveFriendRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// userId - идентификатор пользователя для удаления из друзей
	UserId        string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFriendRequest) Reset() {
	*x = RemoveFriendRequest{}
	mi := &file_api_social_social_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFriendRequest) ProtoMessage() {}

func (x *RemoveFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_social_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFriendRequest.ProtoReflect.Descriptor instead.
func (*RemoveFriendRequest) Descriptor() ([]byte, []int) {
	return file_api_social_social_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveFriendRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// RemoveFriendResponse - ответ RemoveFriend
type RemoveFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFriendResponse) Reset() {
	*x = RemoveFriendResponse{}
	mi := &file_api_social_social_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFriendResponse) ProtoMessage() {}

func (x *RemoveFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_social_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFriendResponse.ProtoReflect.Descriptor instead.
func (*RemoveFriendResponse) Descriptor() ([]byte, []int) {
	return file_api_social_social_proto_rawDescGZIP(), []int{10}
}

// ListFriendsRequest - запрос ListFriends
type ListFriendsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// userId - идентификатор пользователя
	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	// limit - лимит результатов
	Limit int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// cursor - курсор для пагинации
	Cursor        *string `protobuf:"bytes,3,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendsRequest) Reset() {
	*x = ListFriendsRequest{}
	mi := &file_api_social_social_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsRequest) ProtoMessage() {}

func (x *ListFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_social_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsRequest.ProtoReflect.Descriptor instead.
func (*ListFriendsRequest) Descriptor() ([]byte, []int) {
	return file_api_social_social_proto_rawDescGZIP(), []int{11}
}

func (x *ListFriendsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListFriendsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListFriendsRequest) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}

// ListFriendsResponse - ответ ListFriends
type ListFriendsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// friendUserIds - список идентификаторов друзей
	FriendUserIds []string `protobuf:"bytes,1,rep,name=friendUserIds,proto3" json:"friendUserIds,omitempty"`
	// nextCursor - следующий курсор для пагинации
	NextCursor    *string `protobuf:"bytes,2,opt,name=nextCursor,proto3,oneof" json:"nextCursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendsResponse) Reset() {
	*x = ListFriendsResponse{}
	mi := &file_api_social_social_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsResponse) ProtoMessage() {}

func (x *ListFriendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_social_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsResponse.ProtoReflect.Descriptor instead.
func (*ListFriendsResponse) Descriptor() ([]byte, []int) {
	return file_api_social_social_proto_rawDescGZIP(), []int{12}
}

func (x *ListFriendsResponse) GetFriendUserIds() []string {
	if x != nil {
		return x.FriendUserIds
	}
	return nil
}

func (x *ListFriendsResponse) GetNextCursor() string {
	if x != nil && x.NextCursor != nil {
		return *x.NextCursor
	}
	return ""
}

var File_api_social_social_proto protoreflect.FileDescriptor

const file_api_social_social_proto_rawDesc = "" +
	"\n" +
	"\x17api/social/social.proto\x12?github.com.krus210.balun_microservices.protobuf.social.v1.proto\x1a\x1bbuf/validate/validate.proto\"\xd7\x01\n" +
	"\rFriendRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12\x1e\n" +
	"\n" +
	"fromUserId\x18\x02 \x01(\tR\n" +
	"fromUserId\x12\x1a\n" +
	"\btoUserId\x18\x03 \x01(\tR\btoUserId\x12l\n" +
	"\x06status\x18\x04 \x01(\x0e2T.github.com.krus210.balun_microservices.protobuf.social.v1.proto.FriendRequestStatusR\x06status\"6\n" +
	"\x18SendFriendRequestRequest\x12\x1a\n" +
	"\btoUserId\x18\x01 \x01(\tR\btoUserId\"\x91\x01\n" +
	"\x19SendFriendRequestResponse\x12t\n" +
	"\rfriendRequest\x18\x01 \x01(\v2N.github.com.krus210.balun_microservices.protobuf.social.v1.proto.FriendRequestR\rfriendRequest\"1\n" +
	"\x13ListRequestsRequest\x12\x1a\n" +
	"\btoUserId\x18\x01 \x01(\tR\btoUserId\"\x82\x01\n" +
	"\x14ListRequestsResponse\x12j\n" +
	"\brequests\x18\x01 \x03(\v2N.github.com.krus210.balun_microservices.protobuf.social.v1.proto.FriendRequestR\brequests\":\n" +
	"\x1aAcceptFriendRequestRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\"\x93\x01\n" +
	"\x1bAcceptFriendRequestResponse\x12t\n" +
	"\rfriendRequest\x18\x01 \x01(\v2N.github.com.krus210.balun_microservices.protobuf.social.v1.proto.FriendRequestR\rfriendRequest\";\n" +
	"\x1bDeclineFriendRequestRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\"\x94\x01\n" +
	"\x1cDeclineFriendRequestResponse\x12t\n" +
	"\rfriendRequest\x18\x01 \x01(\v2N.github.com.krus210.balun_microservices.protobuf.social.v1.proto.FriendRequestR\rfriendRequest\"-\n" +
	"\x13RemoveFriendRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"\x16\n" +
	"\x14RemoveFriendResponse\"j\n" +
	"\x12ListFriendsRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x1b\n" +
	"\x06cursor\x18\x03 \x01(\tH\x00R\x06cursor\x88\x01\x01B\t\n" +
	"\a_cursor\"o\n" +
	"\x13ListFriendsResponse\x12$\n" +
	"\rfriendUserIds\x18\x01 \x03(\tR\rfriendUserIds\x12#\n" +
	"\n" +
	"nextCursor\x18\x02 \x01(\tH\x00R\n" +
	"nextCursor\x88\x01\x01B\r\n" +
	"\v_nextCursor*\x80\x01\n" +
	"\x13FriendRequestStatus\x12!\n" +
	"\x1dFRIEND_REQUEST_STATUS_PENDING\x10\x00\x12\"\n" +
	"\x1eFRIEND_REQUEST_STATUS_ACCEPTED\x10\x01\x12\"\n" +
	"\x1eFRIEND_REQUEST_STATUS_DECLINED\x10\x022\xc8\t\n" +
	"\rSocialService\x12\xcc\x01\n" +
	"\x11SendFriendRequest\x12Y.github.com.krus210.balun_microservices.protobuf.social.v1.proto.SendFriendRequestRequest\x1aZ.github.com.krus210.balun_microservices.protobuf.social.v1.proto.SendFriendRequestResponse\"\x00\x12\xbd\x01\n" +
	"\fListRequests\x12T.github.com.krus210.balun_microservices.protobuf.social.v1.proto.ListRequestsRequest\x1aU.github.com.krus210.balun_microservices.protobuf.social.v1.proto.ListRequestsResponse\"\x00\x12\xd2\x01\n" +
	"\x13AcceptFriendRequest\x12[.github.com.krus210.balun_microservices.protobuf.social.v1.proto.AcceptFriendRequestRequest\x1a\\.github.com.krus210.balun_microservices.protobuf.social.v1.proto.AcceptFriendRequestResponse\"\x00\x12\xd5\x01\n" +
	"\x14DeclineFriendRequest\x12\\.github.com.krus210.balun_microservices.protobuf.social.v1.proto.DeclineFriendRequestRequest\x1a].github.com.krus210.balun_microservices.protobuf.social.v1.proto.DeclineFriendRequestResponse\"\x00\x12\xbd\x01\n" +
	"\fRemoveFriend\x12T.github.com.krus210.balun_microservices.protobuf.social.v1.proto.RemoveFriendRequest\x1aU.github.com.krus210.balun_microservices.protobuf.social.v1.proto.RemoveFriendResponse\"\x00\x12\xba\x01\n" +
	"\vListFriends\x12S.github.com.krus210.balun_microservices.protobuf.social.v1.proto.ListFriendsRequest\x1aT.github.com.krus210.balun_microservices.protobuf.social.v1.proto.ListFriendsResponse\"\x00B\x1fZ\x1dgateway/pkg/api/social;socialb\x06proto3"

var (
	file_api_social_social_proto_rawDescOnce sync.Once
	file_api_social_social_proto_rawDescData []byte
)

func file_api_social_social_proto_rawDescGZIP() []byte {
	file_api_social_social_proto_rawDescOnce.Do(func() {
		file_api_social_social_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_social_social_proto_rawDesc), len(file_api_social_social_proto_rawDesc)))
	})
	return file_api_social_social_proto_rawDescData
}

var file_api_social_social_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_social_social_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_social_social_proto_goTypes = []any{
	(FriendRequestStatus)(0),             // 0: github.com.krus210.balun_microservices.protobuf.social.v1.proto.FriendRequestStatus
	(*FriendRequest)(nil),                // 1: github.com.krus210.balun_microservices.protobuf.social.v1.proto.FriendRequest
	(*SendFriendRequestRequest)(nil),     // 2: github.com.krus210.balun_microservices.protobuf.social.v1.proto.SendFriendRequestRequest
	(*SendFriendRequestResponse)(nil),    // 3: github.com.krus210.balun_microservices.protobuf.social.v1.proto.SendFriendRequestResponse
	(*ListRequestsRequest)(nil),          // 4: github.com.krus210.balun_microservices.protobuf.social.v1.proto.ListRequestsRequest
	(*ListRequestsResponse)(nil),         // 5: github.com.krus210.balun_microservices.protobuf.social.v1.proto.ListRequestsResponse
	(*AcceptFriendRequestRequest)(nil),   // 6: github.com.krus210.balun_microservices.protobuf.social.v1.proto.AcceptFriendRequestRequest
	(*AcceptFriendRequestResponse)(nil),  // 7: github.com.krus210.balun_microservices.protobuf.social.v1.proto.AcceptFriendRequestResponse
	(*DeclineFriendRequestRequest)(nil),  // 8: github.com.krus210.balun_microservices.protobuf.social.v1.proto.DeclineFriendRequestRequest
	(*DeclineFriendRequestResponse)(nil), // 9: github.com.krus210.balun_microservices.protobuf.social.v1.proto.DeclineFriendRequestResponse
	(*RemoveFriendRequest)(nil),          // 10: github.com.krus210.balun_microservices.protobuf.social.v1.proto.RemoveFriendRequest
	(*RemoveFriendResponse)(nil),         // 11: github.com.krus210.balun_microservices.protobuf.social.v1.proto.RemoveFriendResponse
	(*ListFriendsRequest)(nil),           // 12: github.com.krus210.balun_microservices.protobuf.social.v1.proto.ListFriendsRequest
	(*ListFriendsResponse)(nil),          // 13: github.com.krus210.balun_microservices.protobuf.social.v1.proto.ListFriendsResponse
}
var file_api_social_social_proto_depIdxs = []int32{
	0,  // 0: github.com.krus210.balun_microservices.protobuf.social.v1.proto.FriendRequest.status:type_name -> github.com.krus210.balun_microservices.protobuf.social.v1.proto.FriendRequestStatus
	1,  // 1: github.com.krus210.balun_microservices.protobuf.social.v1.proto.SendFriendRequestResponse.friendRequest:type_name -> github.com.krus210.balun_microservices.protobuf.social.v1.proto.FriendRequest
	1,  // 2: github.com.krus210.balun_microservices.protobuf.social.v1.proto.ListRequestsResponse.requests:type_name -> github.com.krus210.balun_microservices.protobuf.social.v1.proto.FriendRequest
	1,  // 3: github.com.krus210.balun_microservices.protobuf.social.v1.proto.AcceptFriendRequestResponse.friendRequest:type_name -> github.com.krus210.balun_microservices.protobuf.social.v1.proto.FriendRequest
	1,  // 4: github.com.krus210.balun_microservices.protobuf.social.v1.proto.DeclineFriendRequestResponse.friendRequest:type_name -> github.com.krus210.balun_microservices.protobuf.social.v1.proto.FriendRequest
	2,  // 5: github.com.krus210.balun_microservices.protobuf.social.v1.proto.SocialService.SendFriendRequest:input_type -> github.com.krus210.balun_microservices.protobuf.social.v1.proto.SendFriendRequestRequest
	4,  // 6: github.com.krus210.balun_microservices.protobuf.social.v1.proto.SocialService.ListRequests:input_type -> github.com.krus210.balun_microservices.protobuf.social.v1.proto.ListRequestsRequest
	6,  // 7: github.com.krus210.balun_microservices.protobuf.social.v1.proto.SocialService.AcceptFriendRequest:input_type -> github.com.krus210.balun_microservices.protobuf.social.v1.proto.AcceptFriendRequestRequest
	8,  // 8: github.com.krus210.balun_microservices.protobuf.social.v1.proto.SocialService.DeclineFriendRequest:input_type -> github.com.krus210.balun_microservices.protobuf.social.v1.proto.DeclineFriendRequestRequest
	10, // 9: github.com.krus210.balun_microservices.protobuf.social.v1.proto.SocialService.RemoveFriend:input_type -> github.com.krus210.balun_microservices.protobuf.social.v1.proto.RemoveFriendRequest
	12, // 10: github.com.krus210.balun_microservices.protobuf.social.v1.proto.SocialService.ListFriends:input_type -> github.com.krus210.balun_microservices.protobuf.social.v1.proto.ListFriendsRequest
	3,  // 11: github.com.krus210.balun_microservices.protobuf.social.v1.proto.SocialService.SendFriendRequest:output_type -> github.com.krus210.balun_microservices.protobuf.social.v1.proto.SendFriendRequestResponse
	5,  // 12: github.com.krus210.balun_microservices.protobuf.social.v1.proto.SocialService.ListRequests:output_type -> github.com.krus210.balun_microservices.protobuf.social.v1.proto.ListRequestsResponse
	7,  // 13: github.com.krus210.balun_microservices.protobuf.social.v1.proto.SocialService.AcceptFriendRequest:output_type -> github.com.krus210.balun_microservices.protobuf.social.v1.proto.AcceptFriendRequestResponse
	9,  // 14: github.com.krus210.balun_microservices.protobuf.social.v1.proto.SocialService.DeclineFriendRequest:output_type -> github.com.krus210.balun_microservices.protobuf.social.v1.proto.DeclineFriendRequestResponse
	11, // 15: github.com.krus210.balun_microservices.protobuf.social.v1.proto.SocialService.RemoveFriend:output_type -> github.com.krus210.balun_microservices.protobuf.social.v1.proto.RemoveFriendResponse
	13, // 16: github.com.krus210.balun_microservices.protobuf.social.v1.proto.SocialService.ListFriends:output_type -> github.com.krus210.balun_microservices.protobuf.social.v1.proto.ListFriendsResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_social_social_proto_init() }
func file_api_social_social_proto_init() {
	if File_api_social_social_proto != nil {
		return
	}
	file_api_social_social_proto_msgTypes[11].OneofWrappers = []any{}
	file_api_social_social_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_social_social_proto_rawDesc), len(file_api_social_social_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_social_social_proto_goTypes,
		DependencyIndexes: file_api_social_social_proto_depIdxs,
		EnumInfos:         file_api_social_social_proto_enumTypes,
		MessageInfos:      file_api_social_social_proto_msgTypes,
	}.Build()
	File_api_social_social_proto = out.File
	file_api_social_social_proto_goTypes = nil
	file_api_social_social_proto_depIdxs = nil
}
