// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"google.golang.org/grpc"
	"google.golang.org/grpc/reflection"
	"lib/postgres"
	grpc2 "users/internal/app/delivery/grpc"
	"users/internal/app/repository"
	"users/internal/app/usecase"
	"users/internal/config"
	"users/internal/middleware/errors"
	"users/pkg/api"
)

// Injectors from wire.go:

// InitializeApp - injector функция, которую сгенерирует Wire
// Возвращает gRPC сервер и cleanup функцию для закрытия ресурсов
func InitializeApp(ctx context.Context, cfg *config.Config) (*grpc.Server, func(), error) {
	connection, cleanup, err := providePostgresConnection(ctx, cfg)
	if err != nil {
		return nil, nil, err
	}
	transactionManagerAPI := provideTransactionManager(connection)
	usersRepository := provideRepository(transactionManagerAPI)
	usecase := provideUsecase(usersRepository)
	usersController := grpc2.NewUsersController(usecase)
	server := provideGRPCServer(usersController)
	return server, func() {
		cleanup()
	}, nil
}

// wire.go:

// providePostgresConnection создает connection pool для postgres и cleanup функцию
func providePostgresConnection(ctx context.Context, cfg *config.Config) (*postgres.Connection, func(), error) {
	conn, _, err := postgres.New(ctx, postgres.WithHost(cfg.Database.Host), postgres.WithPort(cfg.Database.Port), postgres.WithDatabase(cfg.Database.Name), postgres.WithUser(cfg.Database.User), postgres.WithPassword(cfg.Database.Password), postgres.WithSSLMode(cfg.Database.SSLMode), postgres.WithMaxConnIdleTime(cfg.Database.MaxConnIdleTime))
	if err != nil {
		return nil, nil, err
	}
	cleanup := func() {
		conn.Close()
	}
	return conn, cleanup, nil
}

// provideTransactionManager создает transaction manager
func provideTransactionManager(conn *postgres.Connection) postgres.TransactionManagerAPI {
	return postgres.NewTransactionManager(conn)
}

// provideRepository создает репозиторий и возвращает его как интерфейс
func provideRepository(tm postgres.TransactionManagerAPI) usecase.UsersRepository {
	return repository.NewRepository(tm)
}

// provideUsecase создает usecase и возвращает его как интерфейс
func provideUsecase(repo usecase.UsersRepository) usecase.Usecase {
	return usecase.NewUsecase(repo)
}

// provideGRPCServer создает gRPC сервер с middleware и регистрирует контроллер
func provideGRPCServer(controller *grpc2.UsersController) *grpc.Server {
	server := grpc.NewServer(grpc.ChainUnaryInterceptor(errors.ErrorsUnaryInterceptor()))
	proto_v1.RegisterUsersServiceServer(server, controller)
	reflection.Register(server)

	return server
}
