// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: api/gateway/service.proto

package gateway

import (
	auth "gateway/pkg/api/auth"
	chat "gateway/pkg/api/chat"
	social "gateway/pkg/api/social"
	users "gateway/pkg/api/users"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_gateway_service_proto protoreflect.FileDescriptor

const file_api_gateway_service_proto_rawDesc = "" +
	"\n" +
	"\x19api/gateway/service.proto\x12@github.com.krus210.balun_microservices.protobuf.gateway.v1.proto\x1a\x13api/auth/auth.proto\x1a\x13api/chat/chat.proto\x1a\x17api/social/social.proto\x1a\x15api/users/users.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xc80\n" +
	"\x0eGatewayService\x12\xc4\x02\n" +
	"\bRegister\x12N.github.com.krus210.balun_microservices.protobuf.auth.v1.proto.RegisterRequest\x1aO.github.com.krus210.balun_microservices.protobuf.auth.v1.proto.RegisterResponse\"\x96\x01\x92AsJ6\n" +
	"\x03400\x12/\n" +
	"\x10Invalid argument\x12\x1b\n" +
	"\x19\x1a\x17#/definitions/rpcStatusJ9\n" +
	"\x03409\x122\n" +
	"\x13User already exists\x12\x1b\n" +
	"\x19\x1a\x17#/definitions/rpcStatus\x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/auth/register\x12\xb4\x02\n" +
	"\x05Login\x12K.github.com.krus210.balun_microservices.protobuf.auth.v1.proto.LoginRequest\x1aL.github.com.krus210.balun_microservices.protobuf.auth.v1.proto.LoginResponse\"\x8f\x01\x92AoJ6\n" +
	"\x03400\x12/\n" +
	"\x10Invalid argument\x12\x1b\n" +
	"\x19\x1a\x17#/definitions/rpcStatusJ5\n" +
	"\x03401\x12.\n" +
	"\x0fUnauthenticated\x12\x1b\n" +
	"\x19\x1a\x17#/definitions/rpcStatus\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/auth/login\x12\xbc\x02\n" +
	"\aRefresh\x12M.github.com.krus210.balun_microservices.protobuf.auth.v1.proto.RefreshRequest\x1aN.github.com.krus210.balun_microservices.protobuf.auth.v1.proto.RefreshResponse\"\x91\x01\x92AoJ6\n" +
	"\x03400\x12/\n" +
	"\x10Invalid argument\x12\x1b\n" +
	"\x19\x1a\x17#/definitions/rpcStatusJ5\n" +
	"\x03401\x12.\n" +
	"\x0fUnauthenticated\x12\x1b\n" +
	"\x19\x1a\x17#/definitions/rpcStatus\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/auth/refresh\x12\xd9\x02\n" +
	"\rCreateProfile\x12T.github.com.krus210.balun_microservices.protobuf.users.v1.proto.CreateProfileRequest\x1aU.github.com.krus210.balun_microservices.protobuf.users.v1.proto.CreateProfileResponse\"\x9a\x01\x92AvJ6\n" +
	"\x03400\x12/\n" +
	"\x10Invalid argument\x12\x1b\n" +
	"\x19\x1a\x17#/definitions/rpcStatusJ<\n" +
	"\x03409\x125\n" +
	"\x16Profile already exists\x12\x1b\n" +
	"\x19\x1a\x17#/definitions/rpcStatus\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/users/profiles\x12\xe4\x02\n" +
	"\rUpdateProfile\x12T.github.com.krus210.balun_microservices.protobuf.users.v1.proto.UpdateProfileRequest\x1aU.github.com.krus210.balun_microservices.protobuf.users.v1.proto.UpdateProfileResponse\"\xa5\x01\x92AxJ7\n" +
	"\x03404\x120\n" +
	"\x11Profile not found\x12\x1b\n" +
	"\x19\x1a\x17#/definitions/rpcStatusJ=\n" +
	"\x03409\x126\n" +
	"\x17Nickname already exists\x12\x1b\n" +
	"\x19\x1a\x17#/definitions/rpcStatus\x82\xd3\xe4\x93\x02$:\x01*\x1a\x1f/api/v1/users/profiles/{userId}\x12\xa4\x02\n" +
	"\x0eGetProfileByID\x12U.github.com.krus210.balun_microservices.protobuf.users.v1.proto.GetProfileByIDRequest\x1aV.github.com.krus210.balun_microservices.protobuf.users.v1.proto.GetProfileByIDResponse\"c\x92A9J7\n" +
	"\x03404\x120\n" +
	"\x11Profile not found\x12\x1b\n" +
	"\x19\x1a\x17#/definitions/rpcStatus\x82\xd3\xe4\x93\x02!\x12\x1f/api/v1/users/profiles/{userId}\x12\xc4\x02\n" +
	"\x14GetProfileByNickname\x12[.github.com.krus210.balun_microservices.protobuf.users.v1.proto.GetProfileByNicknameRequest\x1a\\.github.com.krus210.balun_microservices.protobuf.users.v1.proto.GetProfileByNicknameResponse\"q\x92A9J7\n" +
	"\x03404\x120\n" +
	"\x11Profile not found\x12\x1b\n" +
	"\x19\x1a\x17#/definitions/rpcStatus\x82\xd3\xe4\x93\x02/\x12-/api/v1/users/profiles/by-nickname/{nickname}\x12\xe3\x01\n" +
	"\x10SearchByNickname\x12W.github.com.krus210.balun_microservices.protobuf.users.v1.proto.SearchByNicknameRequest\x1aX.github.com.krus210.balun_microservices.protobuf.users.v1.proto.SearchByNicknameResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/users/search\x12\xad\x03\n" +
	"\x11SendFriendRequest\x12Y.github.com.krus210.balun_microservices.protobuf.social.v1.proto.SendFriendRequestRequest\x1aZ.github.com.krus210.balun_microservices.protobuf.social.v1.proto.SendFriendRequestResponse\"\xe0\x01\x92A\xb3\x01J6\n" +
	"\x03400\x12/\n" +
	"\x10Invalid argument\x12\x1b\n" +
	"\x19\x1a\x17#/definitions/rpcStatusJ4\n" +
	"\x03404\x12-\n" +
	"\x0eUser not found\x12\x1b\n" +
	"\x19\x1a\x17#/definitions/rpcStatusJC\n" +
	"\x03409\x12<\n" +
	"\x1dFriend request already exists\x12\x1b\n" +
	"\x19\x1a\x17#/definitions/rpcStatus\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/api/v1/social/friend-requests\x12\xe3\x01\n" +
	"\fListRequests\x12T.github.com.krus210.balun_microservices.protobuf.social.v1.proto.ListRequestsRequest\x1aU.github.com.krus210.balun_microservices.protobuf.social.v1.proto.ListRequestsResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/api/v1/social/friend-requests\x12\x88\x03\n" +
	"\x13AcceptFriendRequest\x12[.github.com.krus210.balun_microservices.protobuf.social.v1.proto.AcceptFriendRequestRequest\x1a\\.github.com.krus210.balun_microservices.protobuf.social.v1.proto.AcceptFriendRequestResponse\"\xb5\x01\x92AyJ7\n" +
	"\x03403\x120\n" +
	"\x11Permission denied\x12\x1b\n" +
	"\x19\x1a\x17#/definitions/rpcStatusJ>\n" +
	"\x03404\x127\n" +
	"\x18Friend request not found\x12\x1b\n" +
	"\x19\x1a\x17#/definitions/rpcStatus\x82\xd3\xe4\x93\x023\x1a1/api/v1/social/friend-requests/{requestId}/accept\x12\x8c\x03\n" +
	"\x14DeclineFriendRequest\x12\\.github.com.krus210.balun_microservices.protobuf.social.v1.proto.DeclineFriendRequestRequest\x1a].github.com.krus210.balun_microservices.protobuf.social.v1.proto.DeclineFriendRequestResponse\"\xb6\x01\x92AyJ7\n" +
	"\x03403\x120\n" +
	"\x11Permission denied\x12\x1b\n" +
	"\x19\x1a\x17#/definitions/rpcStatusJ>\n" +
	"\x03404\x127\n" +
	"\x18Friend request not found\x12\x1b\n" +
	"\x19\x1a\x17#/definitions/rpcStatus\x82\xd3\xe4\x93\x024\x1a2/api/v1/social/friend-requests/{requestId}/decline\x12\x9f\x02\n" +
	"\fRemoveFriend\x12T.github.com.krus210.balun_microservices.protobuf.social.v1.proto.RemoveFriendRequest\x1aU.github.com.krus210.balun_microservices.protobuf.social.v1.proto.RemoveFriendResponse\"b\x92A8J6\n" +
	"\x03404\x12/\n" +
	"\x10Friend not found\x12\x1b\n" +
	"\x19\x1a\x17#/definitions/rpcStatus\x82\xd3\xe4\x93\x02!*\x1f/api/v1/social/friends/{userId}\x12\xd8\x01\n" +
	"\vListFriends\x12S.github.com.krus210.balun_microservices.protobuf.social.v1.proto.ListFriendsRequest\x1aT.github.com.krus210.balun_microservices.protobuf.social.v1.proto.ListFriendsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/social/friends\x12\xe0\x02\n" +
	"\x10CreateDirectChat\x12V.github.com.krus210.balun_microservices.protobuf.chat.v1.proto.CreateDirectChatRequest\x1aW.github.com.krus210.balun_microservices.protobuf.chat.v1.proto.CreateDirectChatResponse\"\x9a\x01\x92AsJ6\n" +
	"\x03400\x12/\n" +
	"\x10Invalid argument\x12\x1b\n" +
	"\x19\x1a\x17#/definitions/rpcStatusJ9\n" +
	"\x03409\x122\n" +
	"\x13Chat already exists\x12\x1b\n" +
	"\x19\x1a\x17#/definitions/rpcStatus\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/v1/chat/direct-chats\x12\xc0\x02\n" +
	"\aGetChat\x12M.github.com.krus210.balun_microservices.protobuf.chat.v1.proto.GetChatRequest\x1aN.github.com.krus210.balun_microservices.protobuf.chat.v1.proto.GetChatResponse\"\x95\x01\x92AoJ7\n" +
	"\x03403\x120\n" +
	"\x11Permission denied\x12\x1b\n" +
	"\x19\x1a\x17#/definitions/rpcStatusJ4\n" +
	"\x03404\x12-\n" +
	"\x0eChat not found\x12\x1b\n" +
	"\x19\x1a\x17#/definitions/rpcStatus\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/chat/chats/{chatId}\x12\xd6\x01\n" +
	"\rListUserChats\x12S.github.com.krus210.balun_microservices.protobuf.chat.v1.proto.ListUserChatsRequest\x1aT.github.com.krus210.balun_microservices.protobuf.chat.v1.proto.ListUserChatsResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/chat/chats\x12\xed\x01\n" +
	"\x0fListChatMembers\x12U.github.com.krus210.balun_microservices.protobuf.chat.v1.proto.ListChatMembersRequest\x1aV.github.com.krus210.balun_microservices.protobuf.chat.v1.proto.ListChatMembersResponse\"+\x82\xd3\xe4\x93\x02%\x12#/api/v1/chat/chats/{chatId}/members\x12\xdd\x02\n" +
	"\vSendMessage\x12Q.github.com.krus210.balun_microservices.protobuf.chat.v1.proto.SendMessageRequest\x1aR.github.com.krus210.balun_microservices.protobuf.chat.v1.proto.SendMessageResponse\"\xa6\x01\x92AqJ6\n" +
	"\x03400\x12/\n" +
	"\x10Invalid argument\x12\x1b\n" +
	"\x19\x1a\x17#/definitions/rpcStatusJ7\n" +
	"\x03403\x120\n" +
	"\x11Permission denied\x12\x1b\n" +
	"\x19\x1a\x17#/definitions/rpcStatus\x82\xd3\xe4\x93\x02,:\x04text\"$/api/v1/chat/chats/{chatId}/messages\x12\xe5\x01\n" +
	"\fListMessages\x12R.github.com.krus210.balun_microservices.protobuf.chat.v1.proto.ListMessagesRequest\x1aS.github.com.krus210.balun_microservices.protobuf.chat.v1.proto.ListMessagesResponse\",\x82\xd3\xe4\x93\x02&\x12$/api/v1/chat/chats/{chatId}/messagesB\xd9\x04\x92A\xb8\x01\x12\x8d\x01\n" +
	"\x19Microservices Gateway API\x12GHTTP Gateway для микросервисной архитектуры\"\"\n" +
	"\vAPI Support\x1a\x13support@example.com2\x031.0*\x02\x01\x022\x10application/json:\x10application/json\n" +
	"Dcom.github.com.krus210.balun_microservices.protobuf.gateway.v1.protoB\fServiceProtoP\x01Z\x1fgateway/pkg/api/gateway;gateway\xa2\x02\bGCKBPGVP\xaa\x02?Github.Com.Krus210.BalunMicroservices.Protobuf.Gateway.V1.Proto\xca\x02?Github\\Com\\Krus210\\BalunMicroservices\\Protobuf\\Gateway\\V1\\Proto\xe2\x02KGithub\\Com\\Krus210\\BalunMicroservices\\Protobuf\\Gateway\\V1\\Proto\\GPBMetadata\xea\x02FGithub::Com::Krus210::BalunMicroservices::Protobuf::Gateway::V1::Protob\x06proto3"

var file_api_gateway_service_proto_goTypes = []any{
	(*auth.RegisterRequest)(nil),                // 0: github.com.krus210.balun_microservices.protobuf.auth.v1.proto.RegisterRequest
	(*auth.LoginRequest)(nil),                   // 1: github.com.krus210.balun_microservices.protobuf.auth.v1.proto.LoginRequest
	(*auth.RefreshRequest)(nil),                 // 2: github.com.krus210.balun_microservices.protobuf.auth.v1.proto.RefreshRequest
	(*users.CreateProfileRequest)(nil),          // 3: github.com.krus210.balun_microservices.protobuf.users.v1.proto.CreateProfileRequest
	(*users.UpdateProfileRequest)(nil),          // 4: github.com.krus210.balun_microservices.protobuf.users.v1.proto.UpdateProfileRequest
	(*users.GetProfileByIDRequest)(nil),         // 5: github.com.krus210.balun_microservices.protobuf.users.v1.proto.GetProfileByIDRequest
	(*users.GetProfileByNicknameRequest)(nil),   // 6: github.com.krus210.balun_microservices.protobuf.users.v1.proto.GetProfileByNicknameRequest
	(*users.SearchByNicknameRequest)(nil),       // 7: github.com.krus210.balun_microservices.protobuf.users.v1.proto.SearchByNicknameRequest
	(*social.SendFriendRequestRequest)(nil),     // 8: github.com.krus210.balun_microservices.protobuf.social.v1.proto.SendFriendRequestRequest
	(*social.ListRequestsRequest)(nil),          // 9: github.com.krus210.balun_microservices.protobuf.social.v1.proto.ListRequestsRequest
	(*social.AcceptFriendRequestRequest)(nil),   // 10: github.com.krus210.balun_microservices.protobuf.social.v1.proto.AcceptFriendRequestRequest
	(*social.DeclineFriendRequestRequest)(nil),  // 11: github.com.krus210.balun_microservices.protobuf.social.v1.proto.DeclineFriendRequestRequest
	(*social.RemoveFriendRequest)(nil),          // 12: github.com.krus210.balun_microservices.protobuf.social.v1.proto.RemoveFriendRequest
	(*social.ListFriendsRequest)(nil),           // 13: github.com.krus210.balun_microservices.protobuf.social.v1.proto.ListFriendsRequest
	(*chat.CreateDirectChatRequest)(nil),        // 14: github.com.krus210.balun_microservices.protobuf.chat.v1.proto.CreateDirectChatRequest
	(*chat.GetChatRequest)(nil),                 // 15: github.com.krus210.balun_microservices.protobuf.chat.v1.proto.GetChatRequest
	(*chat.ListUserChatsRequest)(nil),           // 16: github.com.krus210.balun_microservices.protobuf.chat.v1.proto.ListUserChatsRequest
	(*chat.ListChatMembersRequest)(nil),         // 17: github.com.krus210.balun_microservices.protobuf.chat.v1.proto.ListChatMembersRequest
	(*chat.SendMessageRequest)(nil),             // 18: github.com.krus210.balun_microservices.protobuf.chat.v1.proto.SendMessageRequest
	(*chat.ListMessagesRequest)(nil),            // 19: github.com.krus210.balun_microservices.protobuf.chat.v1.proto.ListMessagesRequest
	(*auth.RegisterResponse)(nil),               // 20: github.com.krus210.balun_microservices.protobuf.auth.v1.proto.RegisterResponse
	(*auth.LoginResponse)(nil),                  // 21: github.com.krus210.balun_microservices.protobuf.auth.v1.proto.LoginResponse
	(*auth.RefreshResponse)(nil),                // 22: github.com.krus210.balun_microservices.protobuf.auth.v1.proto.RefreshResponse
	(*users.CreateProfileResponse)(nil),         // 23: github.com.krus210.balun_microservices.protobuf.users.v1.proto.CreateProfileResponse
	(*users.UpdateProfileResponse)(nil),         // 24: github.com.krus210.balun_microservices.protobuf.users.v1.proto.UpdateProfileResponse
	(*users.GetProfileByIDResponse)(nil),        // 25: github.com.krus210.balun_microservices.protobuf.users.v1.proto.GetProfileByIDResponse
	(*users.GetProfileByNicknameResponse)(nil),  // 26: github.com.krus210.balun_microservices.protobuf.users.v1.proto.GetProfileByNicknameResponse
	(*users.SearchByNicknameResponse)(nil),      // 27: github.com.krus210.balun_microservices.protobuf.users.v1.proto.SearchByNicknameResponse
	(*social.SendFriendRequestResponse)(nil),    // 28: github.com.krus210.balun_microservices.protobuf.social.v1.proto.SendFriendRequestResponse
	(*social.ListRequestsResponse)(nil),         // 29: github.com.krus210.balun_microservices.protobuf.social.v1.proto.ListRequestsResponse
	(*social.AcceptFriendRequestResponse)(nil),  // 30: github.com.krus210.balun_microservices.protobuf.social.v1.proto.AcceptFriendRequestResponse
	(*social.DeclineFriendRequestResponse)(nil), // 31: github.com.krus210.balun_microservices.protobuf.social.v1.proto.DeclineFriendRequestResponse
	(*social.RemoveFriendResponse)(nil),         // 32: github.com.krus210.balun_microservices.protobuf.social.v1.proto.RemoveFriendResponse
	(*social.ListFriendsResponse)(nil),          // 33: github.com.krus210.balun_microservices.protobuf.social.v1.proto.ListFriendsResponse
	(*chat.CreateDirectChatResponse)(nil),       // 34: github.com.krus210.balun_microservices.protobuf.chat.v1.proto.CreateDirectChatResponse
	(*chat.GetChatResponse)(nil),                // 35: github.com.krus210.balun_microservices.protobuf.chat.v1.proto.GetChatResponse
	(*chat.ListUserChatsResponse)(nil),          // 36: github.com.krus210.balun_microservices.protobuf.chat.v1.proto.ListUserChatsResponse
	(*chat.ListChatMembersResponse)(nil),        // 37: github.com.krus210.balun_microservices.protobuf.chat.v1.proto.ListChatMembersResponse
	(*chat.SendMessageResponse)(nil),            // 38: github.com.krus210.balun_microservices.protobuf.chat.v1.proto.SendMessageResponse
	(*chat.ListMessagesResponse)(nil),           // 39: github.com.krus210.balun_microservices.protobuf.chat.v1.proto.ListMessagesResponse
}
var file_api_gateway_service_proto_depIdxs = []int32{
	0,  // 0: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.Register:input_type -> github.com.krus210.balun_microservices.protobuf.auth.v1.proto.RegisterRequest
	1,  // 1: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.Login:input_type -> github.com.krus210.balun_microservices.protobuf.auth.v1.proto.LoginRequest
	2,  // 2: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.Refresh:input_type -> github.com.krus210.balun_microservices.protobuf.auth.v1.proto.RefreshRequest
	3,  // 3: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.CreateProfile:input_type -> github.com.krus210.balun_microservices.protobuf.users.v1.proto.CreateProfileRequest
	4,  // 4: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.UpdateProfile:input_type -> github.com.krus210.balun_microservices.protobuf.users.v1.proto.UpdateProfileRequest
	5,  // 5: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.GetProfileByID:input_type -> github.com.krus210.balun_microservices.protobuf.users.v1.proto.GetProfileByIDRequest
	6,  // 6: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.GetProfileByNickname:input_type -> github.com.krus210.balun_microservices.protobuf.users.v1.proto.GetProfileByNicknameRequest
	7,  // 7: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.SearchByNickname:input_type -> github.com.krus210.balun_microservices.protobuf.users.v1.proto.SearchByNicknameRequest
	8,  // 8: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.SendFriendRequest:input_type -> github.com.krus210.balun_microservices.protobuf.social.v1.proto.SendFriendRequestRequest
	9,  // 9: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.ListRequests:input_type -> github.com.krus210.balun_microservices.protobuf.social.v1.proto.ListRequestsRequest
	10, // 10: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.AcceptFriendRequest:input_type -> github.com.krus210.balun_microservices.protobuf.social.v1.proto.AcceptFriendRequestRequest
	11, // 11: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.DeclineFriendRequest:input_type -> github.com.krus210.balun_microservices.protobuf.social.v1.proto.DeclineFriendRequestRequest
	12, // 12: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.RemoveFriend:input_type -> github.com.krus210.balun_microservices.protobuf.social.v1.proto.RemoveFriendRequest
	13, // 13: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.ListFriends:input_type -> github.com.krus210.balun_microservices.protobuf.social.v1.proto.ListFriendsRequest
	14, // 14: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.CreateDirectChat:input_type -> github.com.krus210.balun_microservices.protobuf.chat.v1.proto.CreateDirectChatRequest
	15, // 15: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.GetChat:input_type -> github.com.krus210.balun_microservices.protobuf.chat.v1.proto.GetChatRequest
	16, // 16: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.ListUserChats:input_type -> github.com.krus210.balun_microservices.protobuf.chat.v1.proto.ListUserChatsRequest
	17, // 17: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.ListChatMembers:input_type -> github.com.krus210.balun_microservices.protobuf.chat.v1.proto.ListChatMembersRequest
	18, // 18: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.SendMessage:input_type -> github.com.krus210.balun_microservices.protobuf.chat.v1.proto.SendMessageRequest
	19, // 19: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.ListMessages:input_type -> github.com.krus210.balun_microservices.protobuf.chat.v1.proto.ListMessagesRequest
	20, // 20: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.Register:output_type -> github.com.krus210.balun_microservices.protobuf.auth.v1.proto.RegisterResponse
	21, // 21: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.Login:output_type -> github.com.krus210.balun_microservices.protobuf.auth.v1.proto.LoginResponse
	22, // 22: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.Refresh:output_type -> github.com.krus210.balun_microservices.protobuf.auth.v1.proto.RefreshResponse
	23, // 23: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.CreateProfile:output_type -> github.com.krus210.balun_microservices.protobuf.users.v1.proto.CreateProfileResponse
	24, // 24: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.UpdateProfile:output_type -> github.com.krus210.balun_microservices.protobuf.users.v1.proto.UpdateProfileResponse
	25, // 25: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.GetProfileByID:output_type -> github.com.krus210.balun_microservices.protobuf.users.v1.proto.GetProfileByIDResponse
	26, // 26: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.GetProfileByNickname:output_type -> github.com.krus210.balun_microservices.protobuf.users.v1.proto.GetProfileByNicknameResponse
	27, // 27: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.SearchByNickname:output_type -> github.com.krus210.balun_microservices.protobuf.users.v1.proto.SearchByNicknameResponse
	28, // 28: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.SendFriendRequest:output_type -> github.com.krus210.balun_microservices.protobuf.social.v1.proto.SendFriendRequestResponse
	29, // 29: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.ListRequests:output_type -> github.com.krus210.balun_microservices.protobuf.social.v1.proto.ListRequestsResponse
	30, // 30: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.AcceptFriendRequest:output_type -> github.com.krus210.balun_microservices.protobuf.social.v1.proto.AcceptFriendRequestResponse
	31, // 31: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.DeclineFriendRequest:output_type -> github.com.krus210.balun_microservices.protobuf.social.v1.proto.DeclineFriendRequestResponse
	32, // 32: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.RemoveFriend:output_type -> github.com.krus210.balun_microservices.protobuf.social.v1.proto.RemoveFriendResponse
	33, // 33: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.ListFriends:output_type -> github.com.krus210.balun_microservices.protobuf.social.v1.proto.ListFriendsResponse
	34, // 34: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.CreateDirectChat:output_type -> github.com.krus210.balun_microservices.protobuf.chat.v1.proto.CreateDirectChatResponse
	35, // 35: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.GetChat:output_type -> github.com.krus210.balun_microservices.protobuf.chat.v1.proto.GetChatResponse
	36, // 36: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.ListUserChats:output_type -> github.com.krus210.balun_microservices.protobuf.chat.v1.proto.ListUserChatsResponse
	37, // 37: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.ListChatMembers:output_type -> github.com.krus210.balun_microservices.protobuf.chat.v1.proto.ListChatMembersResponse
	38, // 38: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.SendMessage:output_type -> github.com.krus210.balun_microservices.protobuf.chat.v1.proto.SendMessageResponse
	39, // 39: github.com.krus210.balun_microservices.protobuf.gateway.v1.proto.GatewayService.ListMessages:output_type -> github.com.krus210.balun_microservices.protobuf.chat.v1.proto.ListMessagesResponse
	20, // [20:40] is the sub-list for method output_type
	0,  // [0:20] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_gateway_service_proto_init() }
func file_api_gateway_service_proto_init() {
	if File_api_gateway_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gateway_service_proto_rawDesc), len(file_api_gateway_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gateway_service_proto_goTypes,
		DependencyIndexes: file_api_gateway_service_proto_depIdxs,
	}.Build()
	File_api_gateway_service_proto = out.File
	file_api_gateway_service_proto_goTypes = nil
	file_api_gateway_service_proto_depIdxs = nil
}
