// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.1
// source: api/users/users.proto

package users

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserProfile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// userId - идентификатор пользователя
	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	// nickname - никнейм пользователя
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// bio - биография пользователя
	Bio *string `protobuf:"bytes,3,opt,name=bio,proto3,oneof" json:"bio,omitempty"`
	// avatarUrl - ссылка на аватар пользователя
	AvatarUrl     *string `protobuf:"bytes,4,opt,name=avatarUrl,proto3,oneof" json:"avatarUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_api_users_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_api_users_users_proto_rawDescGZIP(), []int{0}
}

func (x *UserProfile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserProfile) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserProfile) GetBio() string {
	if x != nil && x.Bio != nil {
		return *x.Bio
	}
	return ""
}

func (x *UserProfile) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

// CreateProfileRequest - запрос CreateProfile
type CreateProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// userId - идентификатор пользователя
	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	// nickname - никнейм пользователя
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// bio - биография пользователя
	Bio *string `protobuf:"bytes,3,opt,name=bio,proto3,oneof" json:"bio,omitempty"`
	// avatarUrl - ссылка на аватар пользователя
	AvatarUrl     *string `protobuf:"bytes,4,opt,name=avatarUrl,proto3,oneof" json:"avatarUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileRequest) Reset() {
	*x = CreateProfileRequest{}
	mi := &file_api_users_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileRequest) ProtoMessage() {}

func (x *CreateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_users_users_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProfileRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateProfileRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CreateProfileRequest) GetBio() string {
	if x != nil && x.Bio != nil {
		return *x.Bio
	}
	return ""
}

func (x *CreateProfileRequest) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

// CreateProfileResponse - ответ CreateProfile
type CreateProfileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// userProfile - профиль пользователя
	UserProfile   *UserProfile `protobuf:"bytes,1,opt,name=userProfile,proto3" json:"userProfile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileResponse) Reset() {
	*x = CreateProfileResponse{}
	mi := &file_api_users_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileResponse) ProtoMessage() {}

func (x *CreateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateProfileResponse) Descriptor() ([]byte, []int) {
	return file_api_users_users_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProfileResponse) GetUserProfile() *UserProfile {
	if x != nil {
		return x.UserProfile
	}
	return nil
}

// UpdateProfileRequest - запрос UpdateProfile
type UpdateProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// userId - идентификатор пользователя
	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	// nickname - никнейм пользователя
	Nickname *string `protobuf:"bytes,2,opt,name=nickname,proto3,oneof" json:"nickname,omitempty"`
	// bio - биография пользователя
	Bio *string `protobuf:"bytes,3,opt,name=bio,proto3,oneof" json:"bio,omitempty"`
	// avatarUrl - ссылка на аватар пользователя
	AvatarUrl     *string `protobuf:"bytes,4,opt,name=avatarUrl,proto3,oneof" json:"avatarUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_api_users_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_users_users_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateProfileRequest) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *UpdateProfileRequest) GetBio() string {
	if x != nil && x.Bio != nil {
		return *x.Bio
	}
	return ""
}

func (x *UpdateProfileRequest) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

// UpdateProfileResponse - ответ UpdateProfile
type UpdateProfileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// userProfile - профиль пользователя
	UserProfile   *UserProfile `protobuf:"bytes,1,opt,name=userProfile,proto3" json:"userProfile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_api_users_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_api_users_users_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProfileResponse) GetUserProfile() *UserProfile {
	if x != nil {
		return x.UserProfile
	}
	return nil
}

// GetProfileByIDRequest - запрос GetProfileByID
type GetProfileByIDRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// userId - идентификатор пользователя
	UserId        string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileByIDRequest) Reset() {
	*x = GetProfileByIDRequest{}
	mi := &file_api_users_users_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileByIDRequest) ProtoMessage() {}

func (x *GetProfileByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_users_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileByIDRequest.ProtoReflect.Descriptor instead.
func (*GetProfileByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_users_users_proto_rawDescGZIP(), []int{5}
}

func (x *GetProfileByIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetProfileByIDResponse - ответ GetProfileByID
type GetProfileByIDResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// userProfile - профиль пользователя
	UserProfile   *UserProfile `protobuf:"bytes,1,opt,name=userProfile,proto3" json:"userProfile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileByIDResponse) Reset() {
	*x = GetProfileByIDResponse{}
	mi := &file_api_users_users_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileByIDResponse) ProtoMessage() {}

func (x *GetProfileByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_users_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileByIDResponse.ProtoReflect.Descriptor instead.
func (*GetProfileByIDResponse) Descriptor() ([]byte, []int) {
	return file_api_users_users_proto_rawDescGZIP(), []int{6}
}

func (x *GetProfileByIDResponse) GetUserProfile() *UserProfile {
	if x != nil {
		return x.UserProfile
	}
	return nil
}

// GetProfileByNicknameRequest - запрос GetProfileByNickname
type GetProfileByNicknameRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// nickname - никнейм пользователя
	Nickname      string `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileByNicknameRequest) Reset() {
	*x = GetProfileByNicknameRequest{}
	mi := &file_api_users_users_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileByNicknameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileByNicknameRequest) ProtoMessage() {}

func (x *GetProfileByNicknameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_users_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileByNicknameRequest.ProtoReflect.Descriptor instead.
func (*GetProfileByNicknameRequest) Descriptor() ([]byte, []int) {
	return file_api_users_users_proto_rawDescGZIP(), []int{7}
}

func (x *GetProfileByNicknameRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

// GetProfileByNicknameResponse - ответ GetProfileByNickname
type GetProfileByNicknameResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// userProfile - профиль пользователя
	UserProfile   *UserProfile `protobuf:"bytes,1,opt,name=userProfile,proto3" json:"userProfile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileByNicknameResponse) Reset() {
	*x = GetProfileByNicknameResponse{}
	mi := &file_api_users_users_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileByNicknameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileByNicknameResponse) ProtoMessage() {}

func (x *GetProfileByNicknameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_users_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileByNicknameResponse.ProtoReflect.Descriptor instead.
func (*GetProfileByNicknameResponse) Descriptor() ([]byte, []int) {
	return file_api_users_users_proto_rawDescGZIP(), []int{8}
}

func (x *GetProfileByNicknameResponse) GetUserProfile() *UserProfile {
	if x != nil {
		return x.UserProfile
	}
	return nil
}

// SearchByNicknameRequest - запрос SearchByNickname
type SearchByNicknameRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// query - запрос для поиска
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// limit - лимит результатов
	Limit         int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchByNicknameRequest) Reset() {
	*x = SearchByNicknameRequest{}
	mi := &file_api_users_users_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchByNicknameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchByNicknameRequest) ProtoMessage() {}

func (x *SearchByNicknameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_users_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchByNicknameRequest.ProtoReflect.Descriptor instead.
func (*SearchByNicknameRequest) Descriptor() ([]byte, []int) {
	return file_api_users_users_proto_rawDescGZIP(), []int{9}
}

func (x *SearchByNicknameRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchByNicknameRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// SearchByNicknameResponse - ответ SearchByNickname
type SearchByNicknameResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// results - список профилей пользователей
	Results       []*UserProfile `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchByNicknameResponse) Reset() {
	*x = SearchByNicknameResponse{}
	mi := &file_api_users_users_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchByNicknameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchByNicknameResponse) ProtoMessage() {}

func (x *SearchByNicknameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_users_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchByNicknameResponse.ProtoReflect.Descriptor instead.
func (*SearchByNicknameResponse) Descriptor() ([]byte, []int) {
	return file_api_users_users_proto_rawDescGZIP(), []int{10}
}

func (x *SearchByNicknameResponse) GetResults() []*UserProfile {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_api_users_users_proto protoreflect.FileDescriptor

const file_api_users_users_proto_rawDesc = "" +
	"\n" +
	"\x15api/users/users.proto\x12>github.com.krus210.balun_microservices.protobuf.users.v1.proto\x1a\x1bbuf/validate/validate.proto\"\x91\x01\n" +
	"\vUserProfile\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x15\n" +
	"\x03bio\x18\x03 \x01(\tH\x00R\x03bio\x88\x01\x01\x12!\n" +
	"\tavatarUrl\x18\x04 \x01(\tH\x01R\tavatarUrl\x88\x01\x01B\x06\n" +
	"\x04_bioB\f\n" +
	"\n" +
	"_avatarUrl\"\xb4\x01\n" +
	"\x14CreateProfileRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x124\n" +
	"\bnickname\x18\x02 \x01(\tB\x18\xbaH\x15r\x132\x11^[a-z0-9_]{3,20}$R\bnickname\x12\x15\n" +
	"\x03bio\x18\x03 \x01(\tH\x00R\x03bio\x88\x01\x01\x12!\n" +
	"\tavatarUrl\x18\x04 \x01(\tH\x01R\tavatarUrl\x88\x01\x01B\x06\n" +
	"\x04_bioB\f\n" +
	"\n" +
	"_avatarUrl\"\x86\x01\n" +
	"\x15CreateProfileResponse\x12m\n" +
	"\vuserProfile\x18\x01 \x01(\v2K.github.com.krus210.balun_microservices.protobuf.users.v1.proto.UserProfileR\vuserProfile\"\xc6\x01\n" +
	"\x14UpdateProfileRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x129\n" +
	"\bnickname\x18\x02 \x01(\tB\x18\xbaH\x15r\x132\x11^[a-z0-9_]{3,20}$H\x00R\bnickname\x88\x01\x01\x12\x15\n" +
	"\x03bio\x18\x03 \x01(\tH\x01R\x03bio\x88\x01\x01\x12!\n" +
	"\tavatarUrl\x18\x04 \x01(\tH\x02R\tavatarUrl\x88\x01\x01B\v\n" +
	"\t_nicknameB\x06\n" +
	"\x04_bioB\f\n" +
	"\n" +
	"_avatarUrl\"\x86\x01\n" +
	"\x15UpdateProfileResponse\x12m\n" +
	"\vuserProfile\x18\x01 \x01(\v2K.github.com.krus210.balun_microservices.protobuf.users.v1.proto.UserProfileR\vuserProfile\"/\n" +
	"\x15GetProfileByIDRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"\x87\x01\n" +
	"\x16GetProfileByIDResponse\x12m\n" +
	"\vuserProfile\x18\x01 \x01(\v2K.github.com.krus210.balun_microservices.protobuf.users.v1.proto.UserProfileR\vuserProfile\"9\n" +
	"\x1bGetProfileByNicknameRequest\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\"\x8d\x01\n" +
	"\x1cGetProfileByNicknameResponse\x12m\n" +
	"\vuserProfile\x18\x01 \x01(\v2K.github.com.krus210.balun_microservices.protobuf.users.v1.proto.UserProfileR\vuserProfile\"E\n" +
	"\x17SearchByNicknameRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\"\x81\x01\n" +
	"\x18SearchByNicknameResponse\x12e\n" +
	"\aresults\x18\x01 \x03(\v2K.github.com.krus210.balun_microservices.protobuf.users.v1.proto.UserProfileR\aresults2\xf4\a\n" +
	"\fUsersService\x12\xbe\x01\n" +
	"\rCreateProfile\x12T.github.com.krus210.balun_microservices.protobuf.users.v1.proto.CreateProfileRequest\x1aU.github.com.krus210.balun_microservices.protobuf.users.v1.proto.CreateProfileResponse\"\x00\x12\xbe\x01\n" +
	"\rUpdateProfile\x12T.github.com.krus210.balun_microservices.protobuf.users.v1.proto.UpdateProfileRequest\x1aU.github.com.krus210.balun_microservices.protobuf.users.v1.proto.UpdateProfileResponse\"\x00\x12\xc1\x01\n" +
	"\x0eGetProfileByID\x12U.github.com.krus210.balun_microservices.protobuf.users.v1.proto.GetProfileByIDRequest\x1aV.github.com.krus210.balun_microservices.protobuf.users.v1.proto.GetProfileByIDResponse\"\x00\x12\xd3\x01\n" +
	"\x14GetProfileByNickname\x12[.github.com.krus210.balun_microservices.protobuf.users.v1.proto.GetProfileByNicknameRequest\x1a\\.github.com.krus210.balun_microservices.protobuf.users.v1.proto.GetProfileByNicknameResponse\"\x00\x12\xc7\x01\n" +
	"\x10SearchByNickname\x12W.github.com.krus210.balun_microservices.protobuf.users.v1.proto.SearchByNicknameRequest\x1aX.github.com.krus210.balun_microservices.protobuf.users.v1.proto.SearchByNicknameResponse\"\x00B\x1dZ\x1bgateway/pkg/api/users;usersb\x06proto3"

var (
	file_api_users_users_proto_rawDescOnce sync.Once
	file_api_users_users_proto_rawDescData []byte
)

func file_api_users_users_proto_rawDescGZIP() []byte {
	file_api_users_users_proto_rawDescOnce.Do(func() {
		file_api_users_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_users_users_proto_rawDesc), len(file_api_users_users_proto_rawDesc)))
	})
	return file_api_users_users_proto_rawDescData
}

var file_api_users_users_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_users_users_proto_goTypes = []any{
	(*UserProfile)(nil),                  // 0: github.com.krus210.balun_microservices.protobuf.users.v1.proto.UserProfile
	(*CreateProfileRequest)(nil),         // 1: github.com.krus210.balun_microservices.protobuf.users.v1.proto.CreateProfileRequest
	(*CreateProfileResponse)(nil),        // 2: github.com.krus210.balun_microservices.protobuf.users.v1.proto.CreateProfileResponse
	(*UpdateProfileRequest)(nil),         // 3: github.com.krus210.balun_microservices.protobuf.users.v1.proto.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),        // 4: github.com.krus210.balun_microservices.protobuf.users.v1.proto.UpdateProfileResponse
	(*GetProfileByIDRequest)(nil),        // 5: github.com.krus210.balun_microservices.protobuf.users.v1.proto.GetProfileByIDRequest
	(*GetProfileByIDResponse)(nil),       // 6: github.com.krus210.balun_microservices.protobuf.users.v1.proto.GetProfileByIDResponse
	(*GetProfileByNicknameRequest)(nil),  // 7: github.com.krus210.balun_microservices.protobuf.users.v1.proto.GetProfileByNicknameRequest
	(*GetProfileByNicknameResponse)(nil), // 8: github.com.krus210.balun_microservices.protobuf.users.v1.proto.GetProfileByNicknameResponse
	(*SearchByNicknameRequest)(nil),      // 9: github.com.krus210.balun_microservices.protobuf.users.v1.proto.SearchByNicknameRequest
	(*SearchByNicknameResponse)(nil),     // 10: github.com.krus210.balun_microservices.protobuf.users.v1.proto.SearchByNicknameResponse
}
var file_api_users_users_proto_depIdxs = []int32{
	0,  // 0: github.com.krus210.balun_microservices.protobuf.users.v1.proto.CreateProfileResponse.userProfile:type_name -> github.com.krus210.balun_microservices.protobuf.users.v1.proto.UserProfile
	0,  // 1: github.com.krus210.balun_microservices.protobuf.users.v1.proto.UpdateProfileResponse.userProfile:type_name -> github.com.krus210.balun_microservices.protobuf.users.v1.proto.UserProfile
	0,  // 2: github.com.krus210.balun_microservices.protobuf.users.v1.proto.GetProfileByIDResponse.userProfile:type_name -> github.com.krus210.balun_microservices.protobuf.users.v1.proto.UserProfile
	0,  // 3: github.com.krus210.balun_microservices.protobuf.users.v1.proto.GetProfileByNicknameResponse.userProfile:type_name -> github.com.krus210.balun_microservices.protobuf.users.v1.proto.UserProfile
	0,  // 4: github.com.krus210.balun_microservices.protobuf.users.v1.proto.SearchByNicknameResponse.results:type_name -> github.com.krus210.balun_microservices.protobuf.users.v1.proto.UserProfile
	1,  // 5: github.com.krus210.balun_microservices.protobuf.users.v1.proto.UsersService.CreateProfile:input_type -> github.com.krus210.balun_microservices.protobuf.users.v1.proto.CreateProfileRequest
	3,  // 6: github.com.krus210.balun_microservices.protobuf.users.v1.proto.UsersService.UpdateProfile:input_type -> github.com.krus210.balun_microservices.protobuf.users.v1.proto.UpdateProfileRequest
	5,  // 7: github.com.krus210.balun_microservices.protobuf.users.v1.proto.UsersService.GetProfileByID:input_type -> github.com.krus210.balun_microservices.protobuf.users.v1.proto.GetProfileByIDRequest
	7,  // 8: github.com.krus210.balun_microservices.protobuf.users.v1.proto.UsersService.GetProfileByNickname:input_type -> github.com.krus210.balun_microservices.protobuf.users.v1.proto.GetProfileByNicknameRequest
	9,  // 9: github.com.krus210.balun_microservices.protobuf.users.v1.proto.UsersService.SearchByNickname:input_type -> github.com.krus210.balun_microservices.protobuf.users.v1.proto.SearchByNicknameRequest
	2,  // 10: github.com.krus210.balun_microservices.protobuf.users.v1.proto.UsersService.CreateProfile:output_type -> github.com.krus210.balun_microservices.protobuf.users.v1.proto.CreateProfileResponse
	4,  // 11: github.com.krus210.balun_microservices.protobuf.users.v1.proto.UsersService.UpdateProfile:output_type -> github.com.krus210.balun_microservices.protobuf.users.v1.proto.UpdateProfileResponse
	6,  // 12: github.com.krus210.balun_microservices.protobuf.users.v1.proto.UsersService.GetProfileByID:output_type -> github.com.krus210.balun_microservices.protobuf.users.v1.proto.GetProfileByIDResponse
	8,  // 13: github.com.krus210.balun_microservices.protobuf.users.v1.proto.UsersService.GetProfileByNickname:output_type -> github.com.krus210.balun_microservices.protobuf.users.v1.proto.GetProfileByNicknameResponse
	10, // 14: github.com.krus210.balun_microservices.protobuf.users.v1.proto.UsersService.SearchByNickname:output_type -> github.com.krus210.balun_microservices.protobuf.users.v1.proto.SearchByNicknameResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_users_users_proto_init() }
func file_api_users_users_proto_init() {
	if File_api_users_users_proto != nil {
		return
	}
	file_api_users_users_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_users_users_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_users_users_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_users_users_proto_rawDesc), len(file_api_users_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_users_users_proto_goTypes,
		DependencyIndexes: file_api_users_users_proto_depIdxs,
		MessageInfos:      file_api_users_users_proto_msgTypes,
	}.Build()
	File_api_users_users_proto = out.File
	file_api_users_users_proto_goTypes = nil
	file_api_users_users_proto_depIdxs = nil
}
