// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package mocks

import (
	"auth/internal/app/models"
	"auth/internal/app/usecase/dto"
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// UsecaseMock implements mm_usecase.Usecase
type UsecaseMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcLogin          func(ctx context.Context, req dto.LoginRequest) (up1 *models.User, err error)
	funcLoginOrigin    string
	inspectFuncLogin   func(ctx context.Context, req dto.LoginRequest)
	afterLoginCounter  uint64
	beforeLoginCounter uint64
	LoginMock          mUsecaseMockLogin

	funcRefresh          func(ctx context.Context, req dto.RefreshRequest) (up1 *models.User, err error)
	funcRefreshOrigin    string
	inspectFuncRefresh   func(ctx context.Context, req dto.RefreshRequest)
	afterRefreshCounter  uint64
	beforeRefreshCounter uint64
	RefreshMock          mUsecaseMockRefresh

	funcRegister          func(ctx context.Context, req dto.RegisterRequest) (up1 *models.User, err error)
	funcRegisterOrigin    string
	inspectFuncRegister   func(ctx context.Context, req dto.RegisterRequest)
	afterRegisterCounter  uint64
	beforeRegisterCounter uint64
	RegisterMock          mUsecaseMockRegister
}

// NewUsecaseMock returns a mock for mm_usecase.Usecase
func NewUsecaseMock(t minimock.Tester) *UsecaseMock {
	m := &UsecaseMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.LoginMock = mUsecaseMockLogin{mock: m}
	m.LoginMock.callArgs = []*UsecaseMockLoginParams{}

	m.RefreshMock = mUsecaseMockRefresh{mock: m}
	m.RefreshMock.callArgs = []*UsecaseMockRefreshParams{}

	m.RegisterMock = mUsecaseMockRegister{mock: m}
	m.RegisterMock.callArgs = []*UsecaseMockRegisterParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mUsecaseMockLogin struct {
	optional           bool
	mock               *UsecaseMock
	defaultExpectation *UsecaseMockLoginExpectation
	expectations       []*UsecaseMockLoginExpectation

	callArgs []*UsecaseMockLoginParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UsecaseMockLoginExpectation specifies expectation struct of the Usecase.Login
type UsecaseMockLoginExpectation struct {
	mock               *UsecaseMock
	params             *UsecaseMockLoginParams
	paramPtrs          *UsecaseMockLoginParamPtrs
	expectationOrigins UsecaseMockLoginExpectationOrigins
	results            *UsecaseMockLoginResults
	returnOrigin       string
	Counter            uint64
}

// UsecaseMockLoginParams contains parameters of the Usecase.Login
type UsecaseMockLoginParams struct {
	ctx context.Context
	req dto.LoginRequest
}

// UsecaseMockLoginParamPtrs contains pointers to parameters of the Usecase.Login
type UsecaseMockLoginParamPtrs struct {
	ctx *context.Context
	req *dto.LoginRequest
}

// UsecaseMockLoginResults contains results of the Usecase.Login
type UsecaseMockLoginResults struct {
	up1 *models.User
	err error
}

// UsecaseMockLoginOrigins contains origins of expectations of the Usecase.Login
type UsecaseMockLoginExpectationOrigins struct {
	origin    string
	originCtx string
	originReq string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmLogin *mUsecaseMockLogin) Optional() *mUsecaseMockLogin {
	mmLogin.optional = true
	return mmLogin
}

// Expect sets up expected params for Usecase.Login
func (mmLogin *mUsecaseMockLogin) Expect(ctx context.Context, req dto.LoginRequest) *mUsecaseMockLogin {
	if mmLogin.mock.funcLogin != nil {
		mmLogin.mock.t.Fatalf("UsecaseMock.Login mock is already set by Set")
	}

	if mmLogin.defaultExpectation == nil {
		mmLogin.defaultExpectation = &UsecaseMockLoginExpectation{}
	}

	if mmLogin.defaultExpectation.paramPtrs != nil {
		mmLogin.mock.t.Fatalf("UsecaseMock.Login mock is already set by ExpectParams functions")
	}

	mmLogin.defaultExpectation.params = &UsecaseMockLoginParams{ctx, req}
	mmLogin.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmLogin.expectations {
		if minimock.Equal(e.params, mmLogin.defaultExpectation.params) {
			mmLogin.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmLogin.defaultExpectation.params)
		}
	}

	return mmLogin
}

// ExpectCtxParam1 sets up expected param ctx for Usecase.Login
func (mmLogin *mUsecaseMockLogin) ExpectCtxParam1(ctx context.Context) *mUsecaseMockLogin {
	if mmLogin.mock.funcLogin != nil {
		mmLogin.mock.t.Fatalf("UsecaseMock.Login mock is already set by Set")
	}

	if mmLogin.defaultExpectation == nil {
		mmLogin.defaultExpectation = &UsecaseMockLoginExpectation{}
	}

	if mmLogin.defaultExpectation.params != nil {
		mmLogin.mock.t.Fatalf("UsecaseMock.Login mock is already set by Expect")
	}

	if mmLogin.defaultExpectation.paramPtrs == nil {
		mmLogin.defaultExpectation.paramPtrs = &UsecaseMockLoginParamPtrs{}
	}
	mmLogin.defaultExpectation.paramPtrs.ctx = &ctx
	mmLogin.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmLogin
}

// ExpectReqParam2 sets up expected param req for Usecase.Login
func (mmLogin *mUsecaseMockLogin) ExpectReqParam2(req dto.LoginRequest) *mUsecaseMockLogin {
	if mmLogin.mock.funcLogin != nil {
		mmLogin.mock.t.Fatalf("UsecaseMock.Login mock is already set by Set")
	}

	if mmLogin.defaultExpectation == nil {
		mmLogin.defaultExpectation = &UsecaseMockLoginExpectation{}
	}

	if mmLogin.defaultExpectation.params != nil {
		mmLogin.mock.t.Fatalf("UsecaseMock.Login mock is already set by Expect")
	}

	if mmLogin.defaultExpectation.paramPtrs == nil {
		mmLogin.defaultExpectation.paramPtrs = &UsecaseMockLoginParamPtrs{}
	}
	mmLogin.defaultExpectation.paramPtrs.req = &req
	mmLogin.defaultExpectation.expectationOrigins.originReq = minimock.CallerInfo(1)

	return mmLogin
}

// Inspect accepts an inspector function that has same arguments as the Usecase.Login
func (mmLogin *mUsecaseMockLogin) Inspect(f func(ctx context.Context, req dto.LoginRequest)) *mUsecaseMockLogin {
	if mmLogin.mock.inspectFuncLogin != nil {
		mmLogin.mock.t.Fatalf("Inspect function is already set for UsecaseMock.Login")
	}

	mmLogin.mock.inspectFuncLogin = f

	return mmLogin
}

// Return sets up results that will be returned by Usecase.Login
func (mmLogin *mUsecaseMockLogin) Return(up1 *models.User, err error) *UsecaseMock {
	if mmLogin.mock.funcLogin != nil {
		mmLogin.mock.t.Fatalf("UsecaseMock.Login mock is already set by Set")
	}

	if mmLogin.defaultExpectation == nil {
		mmLogin.defaultExpectation = &UsecaseMockLoginExpectation{mock: mmLogin.mock}
	}
	mmLogin.defaultExpectation.results = &UsecaseMockLoginResults{up1, err}
	mmLogin.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmLogin.mock
}

// Set uses given function f to mock the Usecase.Login method
func (mmLogin *mUsecaseMockLogin) Set(f func(ctx context.Context, req dto.LoginRequest) (up1 *models.User, err error)) *UsecaseMock {
	if mmLogin.defaultExpectation != nil {
		mmLogin.mock.t.Fatalf("Default expectation is already set for the Usecase.Login method")
	}

	if len(mmLogin.expectations) > 0 {
		mmLogin.mock.t.Fatalf("Some expectations are already set for the Usecase.Login method")
	}

	mmLogin.mock.funcLogin = f
	mmLogin.mock.funcLoginOrigin = minimock.CallerInfo(1)
	return mmLogin.mock
}

// When sets expectation for the Usecase.Login which will trigger the result defined by the following
// Then helper
func (mmLogin *mUsecaseMockLogin) When(ctx context.Context, req dto.LoginRequest) *UsecaseMockLoginExpectation {
	if mmLogin.mock.funcLogin != nil {
		mmLogin.mock.t.Fatalf("UsecaseMock.Login mock is already set by Set")
	}

	expectation := &UsecaseMockLoginExpectation{
		mock:               mmLogin.mock,
		params:             &UsecaseMockLoginParams{ctx, req},
		expectationOrigins: UsecaseMockLoginExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmLogin.expectations = append(mmLogin.expectations, expectation)
	return expectation
}

// Then sets up Usecase.Login return parameters for the expectation previously defined by the When method
func (e *UsecaseMockLoginExpectation) Then(up1 *models.User, err error) *UsecaseMock {
	e.results = &UsecaseMockLoginResults{up1, err}
	return e.mock
}

// Times sets number of times Usecase.Login should be invoked
func (mmLogin *mUsecaseMockLogin) Times(n uint64) *mUsecaseMockLogin {
	if n == 0 {
		mmLogin.mock.t.Fatalf("Times of UsecaseMock.Login mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmLogin.expectedInvocations, n)
	mmLogin.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmLogin
}

func (mmLogin *mUsecaseMockLogin) invocationsDone() bool {
	if len(mmLogin.expectations) == 0 && mmLogin.defaultExpectation == nil && mmLogin.mock.funcLogin == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmLogin.mock.afterLoginCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmLogin.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Login implements mm_usecase.Usecase
func (mmLogin *UsecaseMock) Login(ctx context.Context, req dto.LoginRequest) (up1 *models.User, err error) {
	mm_atomic.AddUint64(&mmLogin.beforeLoginCounter, 1)
	defer mm_atomic.AddUint64(&mmLogin.afterLoginCounter, 1)

	mmLogin.t.Helper()

	if mmLogin.inspectFuncLogin != nil {
		mmLogin.inspectFuncLogin(ctx, req)
	}

	mm_params := UsecaseMockLoginParams{ctx, req}

	// Record call args
	mmLogin.LoginMock.mutex.Lock()
	mmLogin.LoginMock.callArgs = append(mmLogin.LoginMock.callArgs, &mm_params)
	mmLogin.LoginMock.mutex.Unlock()

	for _, e := range mmLogin.LoginMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.up1, e.results.err
		}
	}

	if mmLogin.LoginMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmLogin.LoginMock.defaultExpectation.Counter, 1)
		mm_want := mmLogin.LoginMock.defaultExpectation.params
		mm_want_ptrs := mmLogin.LoginMock.defaultExpectation.paramPtrs

		mm_got := UsecaseMockLoginParams{ctx, req}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmLogin.t.Errorf("UsecaseMock.Login got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmLogin.LoginMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.req != nil && !minimock.Equal(*mm_want_ptrs.req, mm_got.req) {
				mmLogin.t.Errorf("UsecaseMock.Login got unexpected parameter req, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmLogin.LoginMock.defaultExpectation.expectationOrigins.originReq, *mm_want_ptrs.req, mm_got.req, minimock.Diff(*mm_want_ptrs.req, mm_got.req))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmLogin.t.Errorf("UsecaseMock.Login got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmLogin.LoginMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmLogin.LoginMock.defaultExpectation.results
		if mm_results == nil {
			mmLogin.t.Fatal("No results are set for the UsecaseMock.Login")
		}
		return (*mm_results).up1, (*mm_results).err
	}
	if mmLogin.funcLogin != nil {
		return mmLogin.funcLogin(ctx, req)
	}
	mmLogin.t.Fatalf("Unexpected call to UsecaseMock.Login. %v %v", ctx, req)
	return
}

// LoginAfterCounter returns a count of finished UsecaseMock.Login invocations
func (mmLogin *UsecaseMock) LoginAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmLogin.afterLoginCounter)
}

// LoginBeforeCounter returns a count of UsecaseMock.Login invocations
func (mmLogin *UsecaseMock) LoginBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmLogin.beforeLoginCounter)
}

// Calls returns a list of arguments used in each call to UsecaseMock.Login.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmLogin *mUsecaseMockLogin) Calls() []*UsecaseMockLoginParams {
	mmLogin.mutex.RLock()

	argCopy := make([]*UsecaseMockLoginParams, len(mmLogin.callArgs))
	copy(argCopy, mmLogin.callArgs)

	mmLogin.mutex.RUnlock()

	return argCopy
}

// MinimockLoginDone returns true if the count of the Login invocations corresponds
// the number of defined expectations
func (m *UsecaseMock) MinimockLoginDone() bool {
	if m.LoginMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.LoginMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.LoginMock.invocationsDone()
}

// MinimockLoginInspect logs each unmet expectation
func (m *UsecaseMock) MinimockLoginInspect() {
	for _, e := range m.LoginMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UsecaseMock.Login at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterLoginCounter := mm_atomic.LoadUint64(&m.afterLoginCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.LoginMock.defaultExpectation != nil && afterLoginCounter < 1 {
		if m.LoginMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UsecaseMock.Login at\n%s", m.LoginMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UsecaseMock.Login at\n%s with params: %#v", m.LoginMock.defaultExpectation.expectationOrigins.origin, *m.LoginMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcLogin != nil && afterLoginCounter < 1 {
		m.t.Errorf("Expected call to UsecaseMock.Login at\n%s", m.funcLoginOrigin)
	}

	if !m.LoginMock.invocationsDone() && afterLoginCounter > 0 {
		m.t.Errorf("Expected %d calls to UsecaseMock.Login at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.LoginMock.expectedInvocations), m.LoginMock.expectedInvocationsOrigin, afterLoginCounter)
	}
}

type mUsecaseMockRefresh struct {
	optional           bool
	mock               *UsecaseMock
	defaultExpectation *UsecaseMockRefreshExpectation
	expectations       []*UsecaseMockRefreshExpectation

	callArgs []*UsecaseMockRefreshParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UsecaseMockRefreshExpectation specifies expectation struct of the Usecase.Refresh
type UsecaseMockRefreshExpectation struct {
	mock               *UsecaseMock
	params             *UsecaseMockRefreshParams
	paramPtrs          *UsecaseMockRefreshParamPtrs
	expectationOrigins UsecaseMockRefreshExpectationOrigins
	results            *UsecaseMockRefreshResults
	returnOrigin       string
	Counter            uint64
}

// UsecaseMockRefreshParams contains parameters of the Usecase.Refresh
type UsecaseMockRefreshParams struct {
	ctx context.Context
	req dto.RefreshRequest
}

// UsecaseMockRefreshParamPtrs contains pointers to parameters of the Usecase.Refresh
type UsecaseMockRefreshParamPtrs struct {
	ctx *context.Context
	req *dto.RefreshRequest
}

// UsecaseMockRefreshResults contains results of the Usecase.Refresh
type UsecaseMockRefreshResults struct {
	up1 *models.User
	err error
}

// UsecaseMockRefreshOrigins contains origins of expectations of the Usecase.Refresh
type UsecaseMockRefreshExpectationOrigins struct {
	origin    string
	originCtx string
	originReq string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmRefresh *mUsecaseMockRefresh) Optional() *mUsecaseMockRefresh {
	mmRefresh.optional = true
	return mmRefresh
}

// Expect sets up expected params for Usecase.Refresh
func (mmRefresh *mUsecaseMockRefresh) Expect(ctx context.Context, req dto.RefreshRequest) *mUsecaseMockRefresh {
	if mmRefresh.mock.funcRefresh != nil {
		mmRefresh.mock.t.Fatalf("UsecaseMock.Refresh mock is already set by Set")
	}

	if mmRefresh.defaultExpectation == nil {
		mmRefresh.defaultExpectation = &UsecaseMockRefreshExpectation{}
	}

	if mmRefresh.defaultExpectation.paramPtrs != nil {
		mmRefresh.mock.t.Fatalf("UsecaseMock.Refresh mock is already set by ExpectParams functions")
	}

	mmRefresh.defaultExpectation.params = &UsecaseMockRefreshParams{ctx, req}
	mmRefresh.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmRefresh.expectations {
		if minimock.Equal(e.params, mmRefresh.defaultExpectation.params) {
			mmRefresh.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmRefresh.defaultExpectation.params)
		}
	}

	return mmRefresh
}

// ExpectCtxParam1 sets up expected param ctx for Usecase.Refresh
func (mmRefresh *mUsecaseMockRefresh) ExpectCtxParam1(ctx context.Context) *mUsecaseMockRefresh {
	if mmRefresh.mock.funcRefresh != nil {
		mmRefresh.mock.t.Fatalf("UsecaseMock.Refresh mock is already set by Set")
	}

	if mmRefresh.defaultExpectation == nil {
		mmRefresh.defaultExpectation = &UsecaseMockRefreshExpectation{}
	}

	if mmRefresh.defaultExpectation.params != nil {
		mmRefresh.mock.t.Fatalf("UsecaseMock.Refresh mock is already set by Expect")
	}

	if mmRefresh.defaultExpectation.paramPtrs == nil {
		mmRefresh.defaultExpectation.paramPtrs = &UsecaseMockRefreshParamPtrs{}
	}
	mmRefresh.defaultExpectation.paramPtrs.ctx = &ctx
	mmRefresh.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmRefresh
}

// ExpectReqParam2 sets up expected param req for Usecase.Refresh
func (mmRefresh *mUsecaseMockRefresh) ExpectReqParam2(req dto.RefreshRequest) *mUsecaseMockRefresh {
	if mmRefresh.mock.funcRefresh != nil {
		mmRefresh.mock.t.Fatalf("UsecaseMock.Refresh mock is already set by Set")
	}

	if mmRefresh.defaultExpectation == nil {
		mmRefresh.defaultExpectation = &UsecaseMockRefreshExpectation{}
	}

	if mmRefresh.defaultExpectation.params != nil {
		mmRefresh.mock.t.Fatalf("UsecaseMock.Refresh mock is already set by Expect")
	}

	if mmRefresh.defaultExpectation.paramPtrs == nil {
		mmRefresh.defaultExpectation.paramPtrs = &UsecaseMockRefreshParamPtrs{}
	}
	mmRefresh.defaultExpectation.paramPtrs.req = &req
	mmRefresh.defaultExpectation.expectationOrigins.originReq = minimock.CallerInfo(1)

	return mmRefresh
}

// Inspect accepts an inspector function that has same arguments as the Usecase.Refresh
func (mmRefresh *mUsecaseMockRefresh) Inspect(f func(ctx context.Context, req dto.RefreshRequest)) *mUsecaseMockRefresh {
	if mmRefresh.mock.inspectFuncRefresh != nil {
		mmRefresh.mock.t.Fatalf("Inspect function is already set for UsecaseMock.Refresh")
	}

	mmRefresh.mock.inspectFuncRefresh = f

	return mmRefresh
}

// Return sets up results that will be returned by Usecase.Refresh
func (mmRefresh *mUsecaseMockRefresh) Return(up1 *models.User, err error) *UsecaseMock {
	if mmRefresh.mock.funcRefresh != nil {
		mmRefresh.mock.t.Fatalf("UsecaseMock.Refresh mock is already set by Set")
	}

	if mmRefresh.defaultExpectation == nil {
		mmRefresh.defaultExpectation = &UsecaseMockRefreshExpectation{mock: mmRefresh.mock}
	}
	mmRefresh.defaultExpectation.results = &UsecaseMockRefreshResults{up1, err}
	mmRefresh.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmRefresh.mock
}

// Set uses given function f to mock the Usecase.Refresh method
func (mmRefresh *mUsecaseMockRefresh) Set(f func(ctx context.Context, req dto.RefreshRequest) (up1 *models.User, err error)) *UsecaseMock {
	if mmRefresh.defaultExpectation != nil {
		mmRefresh.mock.t.Fatalf("Default expectation is already set for the Usecase.Refresh method")
	}

	if len(mmRefresh.expectations) > 0 {
		mmRefresh.mock.t.Fatalf("Some expectations are already set for the Usecase.Refresh method")
	}

	mmRefresh.mock.funcRefresh = f
	mmRefresh.mock.funcRefreshOrigin = minimock.CallerInfo(1)
	return mmRefresh.mock
}

// When sets expectation for the Usecase.Refresh which will trigger the result defined by the following
// Then helper
func (mmRefresh *mUsecaseMockRefresh) When(ctx context.Context, req dto.RefreshRequest) *UsecaseMockRefreshExpectation {
	if mmRefresh.mock.funcRefresh != nil {
		mmRefresh.mock.t.Fatalf("UsecaseMock.Refresh mock is already set by Set")
	}

	expectation := &UsecaseMockRefreshExpectation{
		mock:               mmRefresh.mock,
		params:             &UsecaseMockRefreshParams{ctx, req},
		expectationOrigins: UsecaseMockRefreshExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmRefresh.expectations = append(mmRefresh.expectations, expectation)
	return expectation
}

// Then sets up Usecase.Refresh return parameters for the expectation previously defined by the When method
func (e *UsecaseMockRefreshExpectation) Then(up1 *models.User, err error) *UsecaseMock {
	e.results = &UsecaseMockRefreshResults{up1, err}
	return e.mock
}

// Times sets number of times Usecase.Refresh should be invoked
func (mmRefresh *mUsecaseMockRefresh) Times(n uint64) *mUsecaseMockRefresh {
	if n == 0 {
		mmRefresh.mock.t.Fatalf("Times of UsecaseMock.Refresh mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmRefresh.expectedInvocations, n)
	mmRefresh.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmRefresh
}

func (mmRefresh *mUsecaseMockRefresh) invocationsDone() bool {
	if len(mmRefresh.expectations) == 0 && mmRefresh.defaultExpectation == nil && mmRefresh.mock.funcRefresh == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmRefresh.mock.afterRefreshCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmRefresh.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Refresh implements mm_usecase.Usecase
func (mmRefresh *UsecaseMock) Refresh(ctx context.Context, req dto.RefreshRequest) (up1 *models.User, err error) {
	mm_atomic.AddUint64(&mmRefresh.beforeRefreshCounter, 1)
	defer mm_atomic.AddUint64(&mmRefresh.afterRefreshCounter, 1)

	mmRefresh.t.Helper()

	if mmRefresh.inspectFuncRefresh != nil {
		mmRefresh.inspectFuncRefresh(ctx, req)
	}

	mm_params := UsecaseMockRefreshParams{ctx, req}

	// Record call args
	mmRefresh.RefreshMock.mutex.Lock()
	mmRefresh.RefreshMock.callArgs = append(mmRefresh.RefreshMock.callArgs, &mm_params)
	mmRefresh.RefreshMock.mutex.Unlock()

	for _, e := range mmRefresh.RefreshMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.up1, e.results.err
		}
	}

	if mmRefresh.RefreshMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmRefresh.RefreshMock.defaultExpectation.Counter, 1)
		mm_want := mmRefresh.RefreshMock.defaultExpectation.params
		mm_want_ptrs := mmRefresh.RefreshMock.defaultExpectation.paramPtrs

		mm_got := UsecaseMockRefreshParams{ctx, req}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmRefresh.t.Errorf("UsecaseMock.Refresh got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRefresh.RefreshMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.req != nil && !minimock.Equal(*mm_want_ptrs.req, mm_got.req) {
				mmRefresh.t.Errorf("UsecaseMock.Refresh got unexpected parameter req, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRefresh.RefreshMock.defaultExpectation.expectationOrigins.originReq, *mm_want_ptrs.req, mm_got.req, minimock.Diff(*mm_want_ptrs.req, mm_got.req))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmRefresh.t.Errorf("UsecaseMock.Refresh got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmRefresh.RefreshMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmRefresh.RefreshMock.defaultExpectation.results
		if mm_results == nil {
			mmRefresh.t.Fatal("No results are set for the UsecaseMock.Refresh")
		}
		return (*mm_results).up1, (*mm_results).err
	}
	if mmRefresh.funcRefresh != nil {
		return mmRefresh.funcRefresh(ctx, req)
	}
	mmRefresh.t.Fatalf("Unexpected call to UsecaseMock.Refresh. %v %v", ctx, req)
	return
}

// RefreshAfterCounter returns a count of finished UsecaseMock.Refresh invocations
func (mmRefresh *UsecaseMock) RefreshAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRefresh.afterRefreshCounter)
}

// RefreshBeforeCounter returns a count of UsecaseMock.Refresh invocations
func (mmRefresh *UsecaseMock) RefreshBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRefresh.beforeRefreshCounter)
}

// Calls returns a list of arguments used in each call to UsecaseMock.Refresh.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmRefresh *mUsecaseMockRefresh) Calls() []*UsecaseMockRefreshParams {
	mmRefresh.mutex.RLock()

	argCopy := make([]*UsecaseMockRefreshParams, len(mmRefresh.callArgs))
	copy(argCopy, mmRefresh.callArgs)

	mmRefresh.mutex.RUnlock()

	return argCopy
}

// MinimockRefreshDone returns true if the count of the Refresh invocations corresponds
// the number of defined expectations
func (m *UsecaseMock) MinimockRefreshDone() bool {
	if m.RefreshMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.RefreshMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.RefreshMock.invocationsDone()
}

// MinimockRefreshInspect logs each unmet expectation
func (m *UsecaseMock) MinimockRefreshInspect() {
	for _, e := range m.RefreshMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UsecaseMock.Refresh at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterRefreshCounter := mm_atomic.LoadUint64(&m.afterRefreshCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.RefreshMock.defaultExpectation != nil && afterRefreshCounter < 1 {
		if m.RefreshMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UsecaseMock.Refresh at\n%s", m.RefreshMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UsecaseMock.Refresh at\n%s with params: %#v", m.RefreshMock.defaultExpectation.expectationOrigins.origin, *m.RefreshMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcRefresh != nil && afterRefreshCounter < 1 {
		m.t.Errorf("Expected call to UsecaseMock.Refresh at\n%s", m.funcRefreshOrigin)
	}

	if !m.RefreshMock.invocationsDone() && afterRefreshCounter > 0 {
		m.t.Errorf("Expected %d calls to UsecaseMock.Refresh at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.RefreshMock.expectedInvocations), m.RefreshMock.expectedInvocationsOrigin, afterRefreshCounter)
	}
}

type mUsecaseMockRegister struct {
	optional           bool
	mock               *UsecaseMock
	defaultExpectation *UsecaseMockRegisterExpectation
	expectations       []*UsecaseMockRegisterExpectation

	callArgs []*UsecaseMockRegisterParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UsecaseMockRegisterExpectation specifies expectation struct of the Usecase.Register
type UsecaseMockRegisterExpectation struct {
	mock               *UsecaseMock
	params             *UsecaseMockRegisterParams
	paramPtrs          *UsecaseMockRegisterParamPtrs
	expectationOrigins UsecaseMockRegisterExpectationOrigins
	results            *UsecaseMockRegisterResults
	returnOrigin       string
	Counter            uint64
}

// UsecaseMockRegisterParams contains parameters of the Usecase.Register
type UsecaseMockRegisterParams struct {
	ctx context.Context
	req dto.RegisterRequest
}

// UsecaseMockRegisterParamPtrs contains pointers to parameters of the Usecase.Register
type UsecaseMockRegisterParamPtrs struct {
	ctx *context.Context
	req *dto.RegisterRequest
}

// UsecaseMockRegisterResults contains results of the Usecase.Register
type UsecaseMockRegisterResults struct {
	up1 *models.User
	err error
}

// UsecaseMockRegisterOrigins contains origins of expectations of the Usecase.Register
type UsecaseMockRegisterExpectationOrigins struct {
	origin    string
	originCtx string
	originReq string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmRegister *mUsecaseMockRegister) Optional() *mUsecaseMockRegister {
	mmRegister.optional = true
	return mmRegister
}

// Expect sets up expected params for Usecase.Register
func (mmRegister *mUsecaseMockRegister) Expect(ctx context.Context, req dto.RegisterRequest) *mUsecaseMockRegister {
	if mmRegister.mock.funcRegister != nil {
		mmRegister.mock.t.Fatalf("UsecaseMock.Register mock is already set by Set")
	}

	if mmRegister.defaultExpectation == nil {
		mmRegister.defaultExpectation = &UsecaseMockRegisterExpectation{}
	}

	if mmRegister.defaultExpectation.paramPtrs != nil {
		mmRegister.mock.t.Fatalf("UsecaseMock.Register mock is already set by ExpectParams functions")
	}

	mmRegister.defaultExpectation.params = &UsecaseMockRegisterParams{ctx, req}
	mmRegister.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmRegister.expectations {
		if minimock.Equal(e.params, mmRegister.defaultExpectation.params) {
			mmRegister.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmRegister.defaultExpectation.params)
		}
	}

	return mmRegister
}

// ExpectCtxParam1 sets up expected param ctx for Usecase.Register
func (mmRegister *mUsecaseMockRegister) ExpectCtxParam1(ctx context.Context) *mUsecaseMockRegister {
	if mmRegister.mock.funcRegister != nil {
		mmRegister.mock.t.Fatalf("UsecaseMock.Register mock is already set by Set")
	}

	if mmRegister.defaultExpectation == nil {
		mmRegister.defaultExpectation = &UsecaseMockRegisterExpectation{}
	}

	if mmRegister.defaultExpectation.params != nil {
		mmRegister.mock.t.Fatalf("UsecaseMock.Register mock is already set by Expect")
	}

	if mmRegister.defaultExpectation.paramPtrs == nil {
		mmRegister.defaultExpectation.paramPtrs = &UsecaseMockRegisterParamPtrs{}
	}
	mmRegister.defaultExpectation.paramPtrs.ctx = &ctx
	mmRegister.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmRegister
}

// ExpectReqParam2 sets up expected param req for Usecase.Register
func (mmRegister *mUsecaseMockRegister) ExpectReqParam2(req dto.RegisterRequest) *mUsecaseMockRegister {
	if mmRegister.mock.funcRegister != nil {
		mmRegister.mock.t.Fatalf("UsecaseMock.Register mock is already set by Set")
	}

	if mmRegister.defaultExpectation == nil {
		mmRegister.defaultExpectation = &UsecaseMockRegisterExpectation{}
	}

	if mmRegister.defaultExpectation.params != nil {
		mmRegister.mock.t.Fatalf("UsecaseMock.Register mock is already set by Expect")
	}

	if mmRegister.defaultExpectation.paramPtrs == nil {
		mmRegister.defaultExpectation.paramPtrs = &UsecaseMockRegisterParamPtrs{}
	}
	mmRegister.defaultExpectation.paramPtrs.req = &req
	mmRegister.defaultExpectation.expectationOrigins.originReq = minimock.CallerInfo(1)

	return mmRegister
}

// Inspect accepts an inspector function that has same arguments as the Usecase.Register
func (mmRegister *mUsecaseMockRegister) Inspect(f func(ctx context.Context, req dto.RegisterRequest)) *mUsecaseMockRegister {
	if mmRegister.mock.inspectFuncRegister != nil {
		mmRegister.mock.t.Fatalf("Inspect function is already set for UsecaseMock.Register")
	}

	mmRegister.mock.inspectFuncRegister = f

	return mmRegister
}

// Return sets up results that will be returned by Usecase.Register
func (mmRegister *mUsecaseMockRegister) Return(up1 *models.User, err error) *UsecaseMock {
	if mmRegister.mock.funcRegister != nil {
		mmRegister.mock.t.Fatalf("UsecaseMock.Register mock is already set by Set")
	}

	if mmRegister.defaultExpectation == nil {
		mmRegister.defaultExpectation = &UsecaseMockRegisterExpectation{mock: mmRegister.mock}
	}
	mmRegister.defaultExpectation.results = &UsecaseMockRegisterResults{up1, err}
	mmRegister.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmRegister.mock
}

// Set uses given function f to mock the Usecase.Register method
func (mmRegister *mUsecaseMockRegister) Set(f func(ctx context.Context, req dto.RegisterRequest) (up1 *models.User, err error)) *UsecaseMock {
	if mmRegister.defaultExpectation != nil {
		mmRegister.mock.t.Fatalf("Default expectation is already set for the Usecase.Register method")
	}

	if len(mmRegister.expectations) > 0 {
		mmRegister.mock.t.Fatalf("Some expectations are already set for the Usecase.Register method")
	}

	mmRegister.mock.funcRegister = f
	mmRegister.mock.funcRegisterOrigin = minimock.CallerInfo(1)
	return mmRegister.mock
}

// When sets expectation for the Usecase.Register which will trigger the result defined by the following
// Then helper
func (mmRegister *mUsecaseMockRegister) When(ctx context.Context, req dto.RegisterRequest) *UsecaseMockRegisterExpectation {
	if mmRegister.mock.funcRegister != nil {
		mmRegister.mock.t.Fatalf("UsecaseMock.Register mock is already set by Set")
	}

	expectation := &UsecaseMockRegisterExpectation{
		mock:               mmRegister.mock,
		params:             &UsecaseMockRegisterParams{ctx, req},
		expectationOrigins: UsecaseMockRegisterExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmRegister.expectations = append(mmRegister.expectations, expectation)
	return expectation
}

// Then sets up Usecase.Register return parameters for the expectation previously defined by the When method
func (e *UsecaseMockRegisterExpectation) Then(up1 *models.User, err error) *UsecaseMock {
	e.results = &UsecaseMockRegisterResults{up1, err}
	return e.mock
}

// Times sets number of times Usecase.Register should be invoked
func (mmRegister *mUsecaseMockRegister) Times(n uint64) *mUsecaseMockRegister {
	if n == 0 {
		mmRegister.mock.t.Fatalf("Times of UsecaseMock.Register mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmRegister.expectedInvocations, n)
	mmRegister.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmRegister
}

func (mmRegister *mUsecaseMockRegister) invocationsDone() bool {
	if len(mmRegister.expectations) == 0 && mmRegister.defaultExpectation == nil && mmRegister.mock.funcRegister == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmRegister.mock.afterRegisterCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmRegister.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Register implements mm_usecase.Usecase
func (mmRegister *UsecaseMock) Register(ctx context.Context, req dto.RegisterRequest) (up1 *models.User, err error) {
	mm_atomic.AddUint64(&mmRegister.beforeRegisterCounter, 1)
	defer mm_atomic.AddUint64(&mmRegister.afterRegisterCounter, 1)

	mmRegister.t.Helper()

	if mmRegister.inspectFuncRegister != nil {
		mmRegister.inspectFuncRegister(ctx, req)
	}

	mm_params := UsecaseMockRegisterParams{ctx, req}

	// Record call args
	mmRegister.RegisterMock.mutex.Lock()
	mmRegister.RegisterMock.callArgs = append(mmRegister.RegisterMock.callArgs, &mm_params)
	mmRegister.RegisterMock.mutex.Unlock()

	for _, e := range mmRegister.RegisterMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.up1, e.results.err
		}
	}

	if mmRegister.RegisterMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmRegister.RegisterMock.defaultExpectation.Counter, 1)
		mm_want := mmRegister.RegisterMock.defaultExpectation.params
		mm_want_ptrs := mmRegister.RegisterMock.defaultExpectation.paramPtrs

		mm_got := UsecaseMockRegisterParams{ctx, req}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmRegister.t.Errorf("UsecaseMock.Register got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRegister.RegisterMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.req != nil && !minimock.Equal(*mm_want_ptrs.req, mm_got.req) {
				mmRegister.t.Errorf("UsecaseMock.Register got unexpected parameter req, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRegister.RegisterMock.defaultExpectation.expectationOrigins.originReq, *mm_want_ptrs.req, mm_got.req, minimock.Diff(*mm_want_ptrs.req, mm_got.req))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmRegister.t.Errorf("UsecaseMock.Register got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmRegister.RegisterMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmRegister.RegisterMock.defaultExpectation.results
		if mm_results == nil {
			mmRegister.t.Fatal("No results are set for the UsecaseMock.Register")
		}
		return (*mm_results).up1, (*mm_results).err
	}
	if mmRegister.funcRegister != nil {
		return mmRegister.funcRegister(ctx, req)
	}
	mmRegister.t.Fatalf("Unexpected call to UsecaseMock.Register. %v %v", ctx, req)
	return
}

// RegisterAfterCounter returns a count of finished UsecaseMock.Register invocations
func (mmRegister *UsecaseMock) RegisterAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRegister.afterRegisterCounter)
}

// RegisterBeforeCounter returns a count of UsecaseMock.Register invocations
func (mmRegister *UsecaseMock) RegisterBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRegister.beforeRegisterCounter)
}

// Calls returns a list of arguments used in each call to UsecaseMock.Register.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmRegister *mUsecaseMockRegister) Calls() []*UsecaseMockRegisterParams {
	mmRegister.mutex.RLock()

	argCopy := make([]*UsecaseMockRegisterParams, len(mmRegister.callArgs))
	copy(argCopy, mmRegister.callArgs)

	mmRegister.mutex.RUnlock()

	return argCopy
}

// MinimockRegisterDone returns true if the count of the Register invocations corresponds
// the number of defined expectations
func (m *UsecaseMock) MinimockRegisterDone() bool {
	if m.RegisterMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.RegisterMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.RegisterMock.invocationsDone()
}

// MinimockRegisterInspect logs each unmet expectation
func (m *UsecaseMock) MinimockRegisterInspect() {
	for _, e := range m.RegisterMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UsecaseMock.Register at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterRegisterCounter := mm_atomic.LoadUint64(&m.afterRegisterCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.RegisterMock.defaultExpectation != nil && afterRegisterCounter < 1 {
		if m.RegisterMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UsecaseMock.Register at\n%s", m.RegisterMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UsecaseMock.Register at\n%s with params: %#v", m.RegisterMock.defaultExpectation.expectationOrigins.origin, *m.RegisterMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcRegister != nil && afterRegisterCounter < 1 {
		m.t.Errorf("Expected call to UsecaseMock.Register at\n%s", m.funcRegisterOrigin)
	}

	if !m.RegisterMock.invocationsDone() && afterRegisterCounter > 0 {
		m.t.Errorf("Expected %d calls to UsecaseMock.Register at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.RegisterMock.expectedInvocations), m.RegisterMock.expectedInvocationsOrigin, afterRegisterCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *UsecaseMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockLoginInspect()

			m.MinimockRefreshInspect()

			m.MinimockRegisterInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *UsecaseMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *UsecaseMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockLoginDone() &&
		m.MinimockRefreshDone() &&
		m.MinimockRegisterDone()
}
